### ISSUE TITLE
pear1u (originally was php71u-pear)

### ISSUE THREAD

**Issue by Jayflux** [iuscommunity/wishlist#104]
### What package do you want?

php71u-pear

### Why?

So we can install the PHP pecl packages

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @Jayflux,

As you have noticed, in the past IUS shipped separate pear packages for each PHP stack (php56-pear, php70u-pear, etc).  After some thought, I think we are going to try to go a different route going forward.

Many PHP extensions are compiled code, so they link against a specific PHP API number (ex. `php(api) = 20160303-64`).  Others are pure PHP code, not compiled, which results in noarch RPMs that aren't tied to a specific version of PHP.  For example, you can use php-tcpdf from EPEL with stock php-common or with php70u-common from IUS.  Pear (and pecl) are pure PHP code.  The only restriction I can find for pear is that they didn't add PHP7-compatibility until version 1.10.0.  Since stock php-pear is version 1.9.4, we can't use that, but a single pear noarch package of at least version 1.10.0 should be able to service all of the IUS PHP stacks.

We have created the [pear1u](https://github.com/iuscommunity-pkg/pear1u) package for your consideration.  I've been using it to build the other php71u packages you requested, and everything is working perfectly so far.  It is already available in the testing repositories, so give it a shot and see how it works for you.

P.S. At this time we do not plan to deprecate our previous pear packages (php56-pear and php70u-pear); rather, we will just start using this single pear1u package for all future PHP stacks (php71u, php72u, etc).  Maybe we'll even get lucky and RHEL8 will come with a new enough version of pear that it isn't even necessary.

**Comment by Jayflux** [comment]
Thanks @carlwgeorge that was both insightful and interesting, good to know.
And yeah if pear is pure PHP code, no need to create new RPMs for each PHP version, I completely agree.

Looks like we now have all the dependencies we need to do some real testing.

**Comment by MatthewDrouin** [comment]
@carlwgeorge Thank you for the help today on freenode. I was able to run `yum --enablerepo ius-testing install pear1u` and get pear installed with php71u and everything seems to be working fine for our application.

**Comment by carlwgeorge** [comment]
Thanks for the feedback @MatthewDrouin.  @Jayflux, let us know how your testing goes as well, but we'll go ahead and proceed with promoting this package.  It will move to the stable repositories during tonight's automation.
