### ISSUE TITLE
php71u-pecl-imagick

### ISSUE THREAD

**Issue by gsdevme** [iuscommunity/wishlist#110]
### What package do you want?

php71u-pecl-imagick

### Why?

This is an extension we were using with php70u

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @gsdevme,

Thanks for your request.  I've done some investigation on this, and it appears that imagick [does not yet have a stable release that compiles with PHP 7.1](https://github.com/mkoppanen/imagick/issues/157).  IUS stands for **I**nline with **U**pstream **S**table, so we would prefer to wait for a compatible stable release.  I subscribed to some [upstream](https://github.com/mkoppanen/imagick/issues/159) [bugs](https://github.com/mkoppanen/imagick/issues/183) so that way I can start work on this once we are able.

**Comment by carlwgeorge** [comment]
Upstream [released version 3.4.3](https://github.com/mkoppanen/imagick/issues/183#issuecomment-276818050).  I have created the [initial package](https://github.com/iuscommunity-pkg/php71u-pecl-imagick/releases/tag/3.4.3-1), and it will move to the testing repositories during tonight's automation.

**Comment by gsdevme** [comment]
@carlwgeorge Hi, thanks! Also sorry for the late reply. I've switched an environment over to the ius-testing and will be testing this over the next few hours.

**Comment by gsdevme** [comment]
I've used the package https://github.com/avalanche123/Imagine to test, however on both 7.0 & 7.1 I see failing builds on the same tests.

Seems to be related to some Grayscale issue, I don't believe this is anything to do with IUS/Imagik more the package.

I can see no issues with the application, therefore I 👍  in terms my ability to test the package is working. 

```
php -i | grep ima
/etc/php.d/40-imagick.ini,
/etc/php.d/imagick.ini,
imagick
imagick module => enabled
imagick module version => 3.4.3
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
Imagick compiled with ImageMagick version => ImageMagick 6.7.2-7 2016-06-16 Q16 http://www.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 6.7.2-7 2016-06-16 Q16 http://www.imagemagick.org
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
proto_text_fetched_decimal => 0
proto_binary_fetched_decimal => 0
```

**Comment by b-harper** [comment]
Hey @gsdevme,

Based on your feedback, this package will get moved to stable repositories during tonight's automation run.  Thanks for testing.

-Ben
