### ISSUE TITLE
php71u-pecl-memcached

### ISSUE THREAD

**Issue by vasillalov** [iuscommunity/wishlist#111]
### What package do you want?

php71u-pecl-memcached

### Why?

Provide ability to store sessions and binary data in memcached clusters. Memcached scales better than Redis and has better mutex capabilities. 

A critical dependency (php71u-pecl-igbinary) has been provided by the upstream vendor. At present, there are debian packages, but none exist for RHEL/CentOS distros.

### OS versions

I would like this package for both RHEL 7, CentOS 7

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Hello @vasillalov,

Unfortunately this request is affected by the same problem detailed in the request for [php70u-pecl-memcached](https://github.com/iuscommunity/wishlist/issues/34).  There is no stable upstream release that supports PHP7 yet.  There isn't even a beta release for us to work with.  Checking open issues, it seems that their [php7 development branch still has segfaults](https://github.com/php-memcached-dev/php-memcached/issues/265).  We're going to have to put this request on hold.

**Comment by jpackagejasonc** [comment]
looks like there should be a release today (or if not today, very very soon): https://github.com/php-memcached-dev/php-memcached/blob/master/ChangeLog#L3

**Comment by carlwgeorge** [comment]
![happening](http://i0.kym-cdn.com/photos/images/original/000/242/631/382.gif)

**Comment by vasillalov** [comment]
AWESOME!





*Vasil LalovSenior Manager of TechnologyGorilla312.361.1487
Directvlalov@gorillagroup.com <vlalov@gorillagroup.com>*

**Comment by carlwgeorge** [comment]
[3.0.1 is on PECL now](https://pecl.php.net/package/memcached/3.0.1), so we will proceed with packaging this.

**Comment by carlwgeorge** [comment]
@vasillalov, your original request was only for EL7.  Is there any interest from you (or anyone else for that matter) to have this for EL6 as well?

**Comment by jpackagejasonc** [comment]
@carlwgeorge definite interest from me for EL6, thanks!

**Comment by jpackagejasonc** [comment]
@carlwgeorge I can definitely see why you made that decision regarding EL6 now that I've built the packages on my own from the EL7 spec. I still would like to see it added though, so just restating my request for EL6 support eventually. thanks!

**Comment by carlwgeorge** [comment]
@jpackagejasonc Don't lose hope, we haven't made a final decision yet.  I just didn't want to delay the EL7 packages due to the situation around libmemcached10 on EL6.  We want to avoid over-extending ourselves by keeping packages around forever, especially considering that EL6 will start [Production 3 Phase](https://access.redhat.com/support/policy/updates/errata/#Production_3_Phase) on [2017-05-10](https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates) (in about three months).  IUS has a general rule to [no longer accept new packages requests for an EL version once it reaches Production 3 Phase](https://ius.io/LifeCycle/#distibution-life-cycle), so that weighs into our decision as well since EL6 is so close to that phase.

**Comment by jpackagejasonc** [comment]
@carlwgeorge makes sense to me. if you do add el6 support will you update this bug or do I need to keep an eye on the repo? and would a PR to add it help at all? I've already done the work and could clean it up for your review

**Comment by carlwgeorge** [comment]
I'll update this issue again.

Thanks for the PR offer, but it isn't necessary.  I already have an uncommitted spec file with the appropriate changes.

**Comment by jpackagejasonc** [comment]
awesome, thanks!

**Comment by carlwgeorge** [comment]
I have updated the spec file to 3.0.3 to address [this issue](https://github.com/iuscommunity/wishlist/issues/34#issuecomment-281131052).  New packages will move to the testing repositories during tonight's automation.

**Comment by jpackagejasonc** [comment]
@carlwgeorge still el7 only for now?

**Comment by carlwgeorge** [comment]
@jpackagejasonc Yes.

**Comment by ammeil** [comment]
Is there still hope to get this for EL6 ?

**Comment by jardeath** [comment]
I'm testing php70u-pecl-memcached from the testing repository on CentOS 7, no issues, however I'm just using WordPress W3 Total Cache plugin to interact with it, which detects it fine and appears to work the same way as it did with php56.

**Comment by tvlooy** [comment]
@carlwgeorge what is holding this back to be committed for EL7? I'm not familiar with iuscommunity way of working

**Comment by carlwgeorge** [comment]
@tvlooy Before promoting new packages to the stable repos, we require user feedback that the packages work as expected (usually from the original requester, but it can be from anyone willing to help test).  Have you tried the packages?  Do they work for you?  We don't need confirmation that every possible thing works, just a basic "works for me" statement (similar to the karma system for Fedora and EPEL packages).

**Comment by ammeil** [comment]
I have tested this package and it appears to be working fine. Thanks @carlwgeorge

**Comment by carlwgeorge** [comment]
Thanks for the feedback @ammeil. The php71u-pecl-memcached-3.0.3-1 EL7 packages will be promoted to our stable repositories during tonight's automation.

**Comment by carlwgeorge** [comment]
I realize that many users would still like to get this package built for EL6.  We are still evaluating if we are going to proceed with that, but if we do this issue will be updated again (despite the closed status).

**Comment by cmkl** [comment]
I could really use this for CentOS 6. I've moved to PHP 7.1 using IUS repository's php71u and there's no php-memcached so all my hosted applications (Wordpress, Drupal, Joomla) have lost the ability to use memecached.

**Comment by carlwgeorge** [comment]
Sorry we were never able to complete this for EL6.

To recap the situation, pecl-memcached needs libmemcached, but the [version in EL6 is too old](https://github.com/php-memcached-dev/php-memcached/issues/146).  In the past we solved for this with libmemcached10.  IUS would like to deprecate that package because it's difficult to maintain.  It's stuck at 1.0.16 because 1.0.18 (the latest) is only [69% backwards compatible on an API/ABI level](http://upstream.rosalinux.ru/versions/libmemcached.html).  As it stands, the only thing requiring libmemcached10 is php56u-pecl-memcached, which will be [retired at the end of the month](https://github.com/iuscommunity/announce/issues/12).

If someone adds a parallel-installable libmemcached 1.0.18 to EPEL for EL6 (using a name like libmemcached1), I can try to build against that.  I just don't have the bandwidth to take that on myself.

**Comment by cmkl** [comment]
Thanks for circling back on this and taking the trouble to explain.

I do appreciate it. 

cmkl

**Comment by carlwgeorge** [comment]
Better late than never, php71u-pecl-memcached is now available for EL6 in the testing repo on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).
