### ISSUE TITLE
lua53u

### ISSUE THREAD

**Issue by Fale** [iuscommunity/wishlist#115]
### What package do you want?

lua 5.3

### Why?

HAProxy version 1.6 and 1.7 include a scripting engine which requries LUA 5.3. HAProxy is compilable without it, but some nice features are lost.
See:
- https://github.com/iuscommunity/wishlist/issues/73
- https://github.com/iuscommunity/wishlist/issues/113

### OS versions

CentOS/RHEL 7

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Thanks for opening this request.  I've got some initial packages done, and I can build haproxy17u against them (https://github.com/iuscommunity/wishlist/issues/113#issuecomment-270781613).  Since this may be used with haproxy16u as well, I went ahead and built this for EL6 and EL7 (since we offer haproxy16u for both).  Would you be willing to test Lua on both EL6 and EL7?  The initial package will move to the testing repositories during tonight's automation.

**Comment by Fale** [comment]
All seems to be ok on EL7, while on EL6, the haproxy16u in the testing repo does not installs lua53u

**Comment by carlwgeorge** [comment]
Sorry for the confusion, I meant to tag you in [this issue](https://github.com/iuscommunity-pkg/haproxy16u/issues/1).  I'll get a build with lua support going so that you can test it.

**Comment by carlwgeorge** [comment]
The [haproxy16u build with lua support (1.6.11-2)](https://github.com/iuscommunity-pkg/haproxy16u/releases/tag/1.6.11-2) is done, and it will move to the testing repositories tonight.

**Comment by carlwgeorge** [comment]
I'll proceed with promoting lua53u to the stable repositories during tonight's automation.  We can track the feedback for haproxy16u's lua support in [this issue](https://github.com/iuscommunity-pkg/haproxy16u/issues/1).
