### ISSUE TITLE
uwsgi-plugin-busyness

### ISSUE THREAD

**Issue by intgr** [iuscommunity/wishlist#117]
### What package do you want?

uwsgi-plugin-busyness 2.0.14

### Why?

Since you're already building uWSGI plugins, maybe it's not too much effort to create a package for the `cheaper_busyness` plugin too. CentOS does not include this plugin in any package.

The busyness plugin includes an advanced algorithm for spawning and stopping worker backend processes based on load. Other algorithms aren't flexible enough to support production workloads when application process startup is expensive. I'm currently limited to static configuration, which is wasteful. Documentation here: https://uwsgi-docs.readthedocs.io/en/latest/Cheaper.html#busyness-cheaper-algorithm

### OS versions

CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Most uwsgi plugins are subpackages of the main uwsgi package (from EPEL, not RHEL/CentOS).  IUS uwsgi plugins are seperate spec files, since it isn't appropriate to add IUS build requirements to an EPEL spec file.  Additionally, it's important to point out that our uwsgi plugins are all tangential to other primary packages that we ship (php70u, python35u, etc).  This plugin is out of scope for IUS, but could possibly be added to the EPEL spec file.  The best course of action is to [open a request on the Red Hat bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=uwsgi) to request that the plugin be added as a subpackage of the EPEL uwsgi package.  I'm a co-maintainer of the EPEL package so I can help attempt to implement it.
