### ISSUE TITLE
subversion

### ISSUE THREAD

**Issue by gtmanfred** [iuscommunity/wishlist#14]
I have customers that want some of the newer features in this, and since yall package git, I think svn would fit with it.

Thanks!

**Comment by carlgeorge** [comment]
Howdy @gtmanfred,

Thanks for reaching out to us. Here is our standard review process for new package requests.

## Is it a good fit for IUS?

More information is needed to determine this.

1. What is the feature?
2. What version of subversion was the feature introduced?
3. What version of RHEL/CentOS is your customer using?

For reference, here are the versions of subversion in RHEL/CentOS.

<table>
    <tr><td>EL5</td><td>1.6.11-12.el5_10</td></tr>
    <tr><td>EL6</td><td>1.6.11-12.el6_6</td></tr>
    <tr><td>EL7</td><td>1.7.14-6.el7</td></tr>
    <tr><td>upstream</td><td>1.8.13</td></tr>
</table>

## Is it maintainable with our current resources?

To be determined.

## After building the package, is the requester willing to test the package to ensure expected behavior?

If we build the package, we won't move it to the stable repositories until you test it to verify it works as expected.

**Comment by b-harper** [comment]
@gtmanfred,

We never heard back from you.  Can we assume you no longer need these packages?

**Comment by gtmanfred** [comment]
I do not need this anymore, but it would still be good to have, and I would be willing to test it.

Having the latest version of svn on at least 7.

Thanks
Daniel

**Comment by carlwgeorge** [comment]
To ensure the best use of our resources, we prefer to package things that will get used, and avoid "good to have" style requests.  We appreciate the offer to test, but since you no longer have a need yourself, I'm going to close out this issue.

If anyone does need a newer version of subversion in the future, feel free to comment here or open a new request.
