### ISSUE TITLE
php56u-pecl-mongodb

### ISSUE THREAD

**Issue by leaf44** [iuscommunity/wishlist#149]
### What new package do you want?

Add the current Mongodb driver for php56
https://pecl.php.net/package/mongodb

### Why?
updated:

The Legacy driver  is currently supplied, but this is no longer supported by newer version of the database or mongo.  RHEL 6 and RHEL 7 only has php56u-pecl-mongod (legacy driver) which is no longer supported by mongo. It would be useful to have this driver/module available for php56u, currently mongodb is only offered for php70u and php71u.

### OS versions

I would like this package for both RHEL 6 and 7 and Centos 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Thanks for opening a request.  The information you provided looks like it still has some of the text from the template ("RHEL 6 only has foobar 1.7.8") and isn't 100% clear.  I believe the problem you have is that we currently only offer the mongodb module for php70u and php71u, but you would like it for php56u.  I have created a [spec file](https://github.com/iuscommunity-pkg/php56u-pecl-mongodb) for that, and packages will move to the testing repositories during tonight's automation.

I only created packages for EL7, because [we stopped accepting new package requests for EL6](https://github.com/iuscommunity/announce/issues/5).

**Comment by leaf44** [comment]
Thanks, that is exactly what we need.

**Comment by b-harper** [comment]
@leaf44,

I just wanted to check in and see if you have had a chance to test this package.  Let us know if it appears to be working for your needs.

**Comment by leaf44** [comment]
I have installed it form the test repository tested this package on centos 7, it seems to be fully functional. I have been been running it for a couple of weeks with no issues. Thanks for putting it up.

**Comment by carlwgeorge** [comment]
Sure thing.  We'll move it to our stable repos.  Thanks for participating in IUS!
