### ISSUE TITLE
libcurl with HTTP/2

### ISSUE THREAD

**Issue by wrossmann** [iuscommunity/wishlist#152]
### What new package do you want?

libcurl >= 7.38.0

### Why?

* As of 7.38.0 HTTP/2 support is added
* Evidently some Apple API our devs need to use more or less *requires* HTTP/2
* People seem to think that HTTP/2 is big deal

### Testing

I agree to test the new package to ensure that it works as expected, by putting it in the dev environment and seeing if the devs start crying. 😈

**Comment by carlwgeorge** [comment]
Hello @wrossmann.

I'm afraid this won't work.  The RHEL versions of curl have the same library soname as the latest upstream (`libcurl.so.4`).  Building a [parallel installable package](https://ius.io/SafeRepo/#parallel-installable-package) would be highly problematic due to file conflicts.  Building a [replacement package](https://ius.io/SafeRepo/#safe-replacement-package) won't work either because applications built against the latest curl will have symbol references that don't exist in stock curl, but the rpm dependency generator won't be able to tell the difference due to the identical library soname.  Additionally, curl is in the core group, so shipping a newer version could break installations in strange ways when IUS is enabled.  To be quite honest curl is just too critical of a library for us to go mucking with it.  We have had bad experiences in the past trying to package newer versions of critical system components.

Sorry we can't help.  If I were in your position I would just use Fedora instead.

**Comment by wrossmann** [comment]
Thanks for looking into it for my @carlwgeorge. I've also been talking to @mojo-iconrad on IRC who has brought up that HTTP/2 support would also require OpenSSL 1.0.2, which would likely carry many of the same concerns.

I'm not particularly familiar with the larger EL ecosystem, would you have any insight on what it would take to get these updated point releases into the base repo short of EL8?

**Comment by carlwgeorge** [comment]
RHEL 7.4 has OpenSSL 1.0.2k.  So does CentOS 7.4.1708, which is supposedly coming out today.  As far as getting HTTP/2 support in stock curl, you could open a [bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&version=7.4&component=curl) asking Red Hat to implement it (either via rebasing curl to a higher version or backporting that feature).  If you pay for RHEL it would also help to open a support case and mention that in the bugzilla.
