### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by xshaldersa** [iuscommunity/wishlist#155]
### What new package do you want?

Composer

### Why?

I want to add Composer package in CentOS 6 

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Hello @xshaldersa.  EL6 is in "[Production 3 Phase](https://access.redhat.com/support/policy/updates/errata/#Production_3_Phase)" and we are no longer accepting new package requests for it.  Even if we were, this request is out of scope for IUS (newer versions of stock packages) because it is not available in stock EL6.  A more appropriate place for this request would be [EPEL](https://fedoraproject.org/wiki/EPEL).  Composer is already available for EPEL7, so I suggest [opening a bug on bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=composer&version=el6) to request it be built for EPEL6 as well.
