### ISSUE TITLE
php71u-pecl-uploadprogress

### ISSUE THREAD

**Issue by NibsNiven** [iuscommunity/wishlist#159]
### What new package do you want?

php71u-pecl-uploadprogress

### Why?

Looks like you have most of php56u-pecl-* upgraded to php7?u, but not php71u-pecl-uploadprogress. It's used by Drupal, so that community would be happy if you made this package.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
This module does not have a PHP7-compatible release.  Read the [equivalent php70u request](https://github.com/iuscommunity/wishlist/issues/36#issuecomment-170939330) for more details.

**Comment by b-harper** [comment]
[This upstream bug][0] has been updated saying the module has been suspended. If a new developer is found, we can reopen this issue.

[0]: https://bugs.php.net/bug.php?id=69242

**Comment by rsajan** [comment]
@b-harper I believe the issue was suspended but not the package. 

As a previous comment on the bugs page you referenced states - if the package was no longer maintained you might see a [highlighted message at the top of the page - as shown here for SQLite](https://pecl.php.net/package/SQLite).

While the [pecl uploadprogress page shows the last release from 2011](https://pecl.php.net/package/uploadprogress) - there was a [pecl uploadprogress release in 2015 available via git.php.net](https://git.php.net/?p=pecl/php/uploadprogress.git)

On the git.php.net page you'll see a commit from 2015-04-19 addressing PHP7 compatibility.

We are deploying to some new PHP 7.1 based servers in the next couple days - and I'll be able to confirm PHP7 compatibility.

**Comment by carlwgeorge** [comment]
The commits on [git.php.net](https://git.php.net/?p=pecl/php/uploadprogress.git) in 2015 do not constitute a release.  The latest release (tag) on [git.php.net](https://git.php.net/?p=pecl/php/uploadprogress.git) is still 1.0.3.1 from 2011.  Once a PHP7-compatible release has occurred we can re-evaluate this request.
