### ISSUE TITLE
Please provide a package for PHP's 'uploadprogress' PECL extension

### ISSUE THREAD

**Issue by mattiasgeniar** [iuscommunity/wishlist#16]
PHP has a rather popular PECL package called "uploadprogress", used by default in Drupal installations when the extension is detected: https://pecl.php.net/package/uploadprogress

It would be very useful if this existed as a "php56u-pecl-uploadprogress", "php55-pecl-uploadprogress" and "php54-pecl-uploadprogress" package.

Many thanks for providing the repositories already, all CentOS users are incredibly grateful for the packages you provide!

**Comment by carlgeorge** [comment]
Howdy @mattiasgeniar,

Thanks for reaching out to us.  Here is our review process for new package requests.

#### Is it a good fit for IUS?

Increasing the appeal of using IUS packages with Drupal is certainly something we are interested in.  The only negative thing is that this extension does not already exist in base RHEL/CentOS.  That is normally a requirement for [primary packages](https://iuscommunity.org/pages/IUSClientUsageGuide.html#primary-packages); however, we consider PECL modules to be [secondary packages](https://iuscommunity.org/pages/IUSClientUsageGuide.html#secondary-supporting-packages), so that isn't a deal breaker.

#### Is it maintainable with our current resources?

Maintainability looks good initially.  The last stable release of this module was over four years ago.  I'm investigating now to determine how bad the build requirements would be.

#### After building the package, is the requester willing to test the package to ensure expected behavior?

Just respond and let us know if you are OK with this.

**Comment by carlgeorge** [comment]
Oh and one more thing; PHP 5.4 will be EOL next month.  When that happens, we will be moving our php54 package out of our stable repo and into our archive repo.  It doesn't make much sense for us to create a php54 version of this module at this point.

**Comment by mattiasgeniar** [comment]
Hi @carlgeorge !

>  After building the package, is the requester willing to test the package to ensure expected behavior?

Definitely. 

>  It doesn't make much sense for us to create a php54 version of this module at this point.

That's a very valid point and a decision I completely understand.

**Comment by carlgeorge** [comment]
The initial [spec file](https://github.com/iuscommunity-pkg/php56u-pecl-uploadprogress) has been written, and I have completed some initial packages from this spec built for RHEL/CentOS 6/7.  They will move to the testing repos tonight.  Give them a shot and let me know what you think.  If things go well I'll look at duplicating the spec file for the php55u stack as well.

**Comment by mattiasgeniar** [comment]
This is working exactly as intended.

```
yum install php56u-pecl-uploadprogress
```

```
$ php -i | grep uploadprogress
/etc/php.d/20-uploadprogress.ini,
uploadprogress
uploadprogress support => enabled
uploadprogress.file.contents_template => /tmp/upload_contents_%s => /tmp/upload_contents_%s
uploadprogress.file.filename_template => /tmp/upt_%s.txt => /tmp/upt_%s.txt
uploadprogress.get_contents => 0 => 0
```

```
$ php -m | grep uploadprogress
uploadprogress
```

Great work!

**Comment by carlgeorge** [comment]
I have also completed builds of this package against the php55u branch.  They will move to the testing repos tonight.  Please have at look at those as well, and if all looks well I'll move all these new packages into the stable repos.

**Comment by carlgeorge** [comment]
I went ahead and tagged php**56**u-pecl-uploadprogress to move to the stable repositories.  Let me know when you get a chance to test php**55**u-pecl-uploadprogress; until we hear back it will stay in the testing repositories.

**Comment by mattiasgeniar** [comment]
Hi Carl,

Sorry for not replying earlier. I tested the php55u package as well, worked like a charm.
Same results as the PHP 5.6 package.

Thanks for the great work!

Mattias

**Comment by carlgeorge** [comment]
Thanks for the feedback Mattias, php55u-pecl-uploadprogress will move to the stable repositories during tonight's automation.  Thanks for participating in the IUS project!
