### ISSUE TITLE
haproxy18u

### ISSUE THREAD

**Issue by dexxtreme** [iuscommunity/wishlist#161]
### What new package do you want?

HAProxy 1.8

### Why?

In version 1.8, they introduced support for HTTP/2.0.

### Testing

I agree to test the new package to ensure that it works as expected. I am only able to test this on CentOS 7.

**Comment by b-harper** [comment]
Hey @dexxtreme,

Thanks for the request.  Seeing that we already package HAProxy, clearly it is a good fit for IUS.  We will take a closer look and update this issue when there is more information.

**Comment by carlwgeorge** [comment]
I sent a [pull request to the Fedora spec file](https://src.fedoraproject.org/rpms/haproxy/pull-request/1) to reduce the amount of changes we need to make when we fork.

**Comment by kustodian** [comment]
We are also interested in 1.8. We also need new features in 1.8 and we are willing to test it as soon as the package is available (if you decide to support it).

**Comment by guillemlc** [comment]
We are also very interested in 1.8 I would also agree to help testing the package. Thanks.

**Comment by carlwgeorge** [comment]
The [initial release](https://github.com/iuscommunity-pkg/haproxy18u/releases/tag/1.8.3-1) of haproxy18u will move to the testing repos during tonight's automation.  Once we get feedback that it works as expected, we'll promote it to the stable repos.

**Comment by kustodian** [comment]
@carlwgeorge should we leave feedback here, or in the haproxy18u repository?

For now I have two suggestions and one of them I think is mandatory, because I built HAProxy 1.8 by myself a few weeks ago:
 * `USE_SYSTEMD=1` should be set while running `make` if you want systemd support to be compiled (which is needed for the `-Ws` parameter which is used in the unit file)
* HAProxy 1.8 supports seamless reloads, so the default config should supported them, I don't see a reason why not to support it. The only thing that would need to be done is add `expose-fd listeners` to the stats socket, so the whole line should look like this:
    ```
    stats socket /var/lib/haproxy/stats expose-fd listeners
    ```
    Also if the user removes that from the config, regular reloads will still work. 

Regarding HAProxy seamless reloads, they are currently with systemd ([source 1](https://discourse.haproxy.org/t/seamless-reloads-dont-work-with-systemd/1954), [source 2](https://www.mail-archive.com/haproxy@formilux.org/msg28585.html)), but regular reloads like in previous versions works without any issues, so it's not a big deal. HAProxy devs are working on the issue.

**Comment by carlwgeorge** [comment]
Thanks @kustodian, here is fine since the package hasn't been promoted to the stable repos yet.  Once it has, and we close this issue, feedback should be directed at the [haproxy18u repository](https://github.com/iuscommunity-pkg/haproxy18u).

I was actually just looking into the `USE_SYSTEMD` variable.  The Fedora spec file is missing it as well, which is what we forked this spec file from.  We'll add it to our spec file and rebuild.  We should also get it reported to Fedora so they can correct it to.  Would you like to [open a bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=haproxy) for them?

If the seamless reloads aren't fully cooperating with systemd yet, I don't see the need to enable them by default.  We can always re-evaluate this later.

**Comment by kustodian** [comment]
I'll open an issue to to Fedore tomorrow, not a problem.

Regarding seamless reloads, adding `expose-fd listeners` won't affect regular reloads in anyway because that is the fallback reload anyway. Here is the output with `expose-fd listeners`:
```
Jan 18 22:57:09 rpmbuild-c7 haproxy[14225]: [WARNING] 017/225704 (14225) : Reexecuting Master process
Jan 18 22:57:09 rpmbuild-c7 haproxy[14225]: [WARNING] 017/225709 (14225) : Failed to connect to the old process socket '/var/lib/haproxy/stats'
Jan 18 22:57:09 rpmbuild-c7 haproxy[14225]: [ALERT] 017/225709 (14225) : Failed to get the sockets from the old process!
Jan 18 22:57:09 rpmbuild-c7 haproxy[14225]: [WARNING] 017/225709 (14225) : Former worker 14252 exited with code 0
```
and without it in the config file:
```
Jan 18 22:56:46 rpmbuild-c7 haproxy[14225]: [WARNING] 017/225637 (14225) : Reexecuting Master process
Jan 18 22:56:46 rpmbuild-c7 haproxy[14225]: [WARNING] 017/225646 (14225) : Former worker 14227 exited with code 0
```
So it just tries to do a seamless reload, if it doesn't work, it just does the regular one.

**Comment by carlwgeorge** [comment]
I've created another [release](https://github.com/iuscommunity-pkg/haproxy18u/releases/tag/1.8.3-2) to [address the systemd issue](https://github.com/iuscommunity-pkg/haproxy18u/commit/73ccb048beacc3ba59fa4cf8e3cae11cf1eb2387).  That will move to the testing repos later tonight.

**Comment by b-harper** [comment]
Just wanted to check in and see if anyone has had a chance to test the updated haproxy18u packages.

**Comment by joseph-pg** [comment]
Hi, @b-harper,

I just tested it and it works. Seamless reload works perfectly.

**Comment by b-harper** [comment]
@joseph-pg,

Thanks for the feedback.  These packages will get moved to the stable repositories after tonight's automation run.

**Comment by kustodian** [comment]
I know this issue has been closed, but I would like to add a note about seamless reloads that @joseph-pg mentioned. Seamless reloads currently don't work when used with systemd, only regular reloads work. There is a bug in HAProxy which is still there in version 1.8.4. Hopefully next version will add a fix.
