### ISSUE TITLE
php72u-pecl-mongodb

### ISSUE THREAD

**Issue by dvorakjan** [iuscommunity/wishlist#173]
### What new package do you want?

php72u-pecl-mongodb

### Why?

PECL mongodb driver is already compatible with PHP 7.2.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @dvorakjan,

Thanks for submitting this request.  This request is a good fit for IUS and we will take a look at get some packages created.

**Comment by b-harper** [comment]
Some packages have been built off of [this spec file][0] and will be hitting the testing repositories after tonight's automation run.


[0]: https://github.com/iuscommunity-pkg/php72u-pecl-mongodb

**Comment by b-harper** [comment]
Hey @dvorakjan,

I just want to check in and see if you had a chance to test this package.  Also note, this package will be moved to the development repertoires after tonight's automation run. We are making some minor changes on how we handle new package requests will be being using the development repertoires instead of the testing repertoires.

**Comment by dvorakjan** [comment]
We have already tested this package and it seems to work correctly. Thank you very much.

**Comment by b-harper** [comment]
@dvorakjan,

Thanks for the feedback.  This package will get moved into the stable repositories during tonight's automation run.
