### ISSUE TITLE
MariaDB ODBC connector driver

### ISSUE THREAD

**Issue by johnnybubonic** [iuscommunity/wishlist#191]
### What new package do you want?

mariadb-connector-odbc 3.0.3

### Why?

(See also: https://github.com/iuscommunity-pkg/mariadb101u/issues/9)

RH/CentOS mysql-connector-odbc does not work with mariadb101u-* packages (and, I suspect though have not tested, mariadb100u-* as well).

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

### Extra information

Downloads are available at https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.0.3/
I have confirmed that the binary release for RHEL7 (mariadb-connector-odbc-3.0.3-ga-rhel7-x86_64.tar.gz) works on CentOS 7 (with mariadb101u), but did not try building from source.

Further information can be found at https://mariadb.com/kb/en/library/about-mariadb-connector-odbc/.

**Comment by carlwgeorge** [comment]
At first I thought this software was tied close enough with mariadb that I would need to build it independently for each of our mariadb packages, but that is not the case.  It is independent software for the most part.  As such we can evaluate it's fit for IUS independently.

IUS has the limited scope of only packaging newer versions of base packages.  Since mariadb-connector-odbc is not packaged in base, it is out of scope for IUS, but is eligible for EPEL.  It has a build requirement of mariadb-connector-c, which has [already been requested for EPEL](https://bugzilla.redhat.com/show_bug.cgi?id=1652293).  Once that request is resolved, a similar request can be filed for mariadb-connector-odbc.
