### ISSUE TITLE
new platform request: Amazon Linux 2

### ISSUE THREAD

**Issue by jpackagejasonc** [iuscommunity/wishlist#199]
### What new platform do you want?

Amazon Linux 2 - https://aws.amazon.com/amazon-linux-2/

### Why?

It's a platform that is just different enough from RHEL 7 rebuild projects like CentOS that I'm hoping to get a statement from IUS on whether official support will be added. If this is the wrong place to make such a request I'll be happy to file elsewhere. Thanks!

**Comment by carlwgeorge** [comment]
I'm aware of Amazon Linux.  Last time I looked at it, it was a mix of RHEL6, RHEL7, and Fedora RPMs.  It also already included several alternate versions of newer packages like http24 and python27.  Because of this there are no plans to build IUS packages for it.  What IUS packages are you looking for that aren't already provided by Amazon?

**Comment by jpackagejasonc** [comment]
@carlwgeorge I'm in the evaluation phase and seeing what the pros and cons are so I don't have a specific request. the IUS offerings are more feature rich compared to the amazon-linux-extras repos from what I've found so far but I agree there is overlap. this issue was just so I could see whether there was any plans on the IUS side to add support, which atm sounds like no. thanks!

**Comment by carlwgeorge** [comment]
I am curious, so once you get deeper into your evaluation, feel free to reply back here with more details.
