### ISSUE TITLE
httpd-itk for httpd24u

### ISSUE THREAD

**Issue by jpackagejasonc** [iuscommunity/wishlist#2]
the version of httpd-itk in epel is the one that matches httpd 2.2 shipped with el6, it would be nice if we could get a httpd24u-itk package of 2.4.x to go with httpd24u.
* itk can be found at: http://mpm-itk.sesse.net/
* current el6 epel srpm can be found at: https://dl.fedoraproject.org/pub/epel/6/SRPMS/httpd-itk-2.2.22-7.el6.src.rpm

**Comment by cgtx** [comment]
Howdy Jason,

Here is our review process for new packages.

1. Is it a good fit for IUS?
2. Is it maintainable with our current resources?
3. After building the package, is the requester willing to test the package to ensure expected behavior?

I feel it is a good fit for IUS.  The Fedora spec file I ported from was pretty straightforward, with no additional dependencies, so it should be maintainable.

https://github.com/iuscommunity-pkg/httpd24u-itk

I have built some initial packages and they will hit the testing repos tonight.  Once they sync to your local mirror, try them out and let us know how they work for you.

```
yum --enablerepo=ius-testing install httpd24u-itk
```

**Comment by cgtx** [comment]
Our package httpd24u is only for el6.  Stock httpd on el7 is already 2.4.  EPEL7 already has [httpd-itk](http://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/httpd-itk.html).

**Comment by cgtx** [comment]
@Alexhha Looks like httpd-itk in EPEL7 is broken.

https://bugzilla.redhat.com/show_bug.cgi?id=1188159
https://bugzilla.redhat.com/show_bug.cgi?id=1059143

After reading those bug reports, it appears that the EPEL7 package can be fixed after RHEL 7.1 is released.

**Comment by cgtx** [comment]
@jpackagejasonc Have you had a chance to test this package yet?

**Comment by cgtx** [comment]
Due to lack of feedback, I'm moving this package to our development repos.
