### ISSUE TITLE
Cython

### ISSUE THREAD

**Issue by jmarshall** [iuscommunity/wishlist#201]
### What new package do you want?

Cython, or really python36u-Cython et al.

### Why?

We are running CentOS 7, and have various scientific software requiring python 3.x (and 3.5+ for recent versions) and using packages that are built via Cython.

EPEL 7 contains a python34-Cython rpm, but because of up-to-date [Snakemake](https://snakemake.readthedocs.io/en/stable/)'s 3.5 requirement, our preferred Python 3 to install is IUS's python36u. There are also Cython-based packages that we need to install, so it would be good to have a Cython rpm that works well with the preferred Python 3.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
EPEL's [python3 (python34 and python36) stack](https://fedoraproject.org/wiki/User:Bkabrda/EPEL7_Python3) is interesting.  In order to enable more packages with less duplication, python2, python34, and python36 subpackages can be built from the same EPEL spec file.  If a package exists in RHEL, a python3-example spec file can be submitted to EPEL to build just the python34 and python36 subpackages.  The later is the case with Cython.

* stock RHEL package
```
$ repoquery --source Cython       
Cython-0.19-5.el7.src.rpm
```

* EPEL package
```
$ repoquery --source python34-Cython
python3-Cython-0.23.5-1.el7.src.rpm
```

Since it's already approved in EPEL, it would be better to just add the python36-Cython subpackage to the python3-Cython spec file, rather than maintaining a duplicate spec file in IUS.  You can submit that request [via bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=python3-Cython&version=epel7).

**Comment by jmarshall** [comment]
Thanks for the information — I'll file some EPEL requests.

The reasons we found so far for preferring IUS's python36u family were: you're packaging python36u-psycopg2; and your python36u-devel package is nicely self-contained whereas EPEL's python36-devel pulls in dozens of other packages notably a bunch of Perl(!) modules.

However python-psycopg2 exists in RHEL so I can submit a similar request for python36-psycopg2, and I guess we can live with the -devel madness.

**Comment by carlwgeorge** [comment]
Thanks for opening those, I'm going to try to help get those resolved.

I see what you mean about the perl dependencies, and the difference is [python36-devel requires redhat-rpm-config](https://src.fedoraproject.org/rpms/python36/blob/epel7/f/python36.spec#_437-441).  It seems to be a necessary evil, and has been discussed in depth.  More than likely I'll make the same change to python36u at some point.

* https://bugzilla.redhat.com/show_bug.cgi?id=1218294
* https://bugzilla.redhat.com/show_bug.cgi?id=1496757
* https://bugzilla.redhat.com/show_bug.cgi?id=1217376

**Comment by jmarshall** [comment]
Great, thanks :smile:

I figured the python36-devel thing probably came down to “It also contains the necessary macros to build RPM packages with Python modules” (gee, maybe that could be in a python36-devel-rpmbuilding sub-package?). Anyway, not the end of the world, though after building local RPMs for lots of system stuff ourselves on CentOS 6, we're trying to avoid that now we're finally upgrading to 7…
