### ISSUE TITLE
libwebp v1.0.0

### ISSUE THREAD

**Issue by futureweb** [iuscommunity/wishlist#202]
### What new package do you want?

libwebp v1.0.0 (https://github.com/webmproject/libwebp/releases)

### Why?

1.0.0 got lot's of improvements (especially Image Quality & encoding performance, memory usage reductions, ...) over 0.3.0 which is delivered with RHEL 7.
Maybe 1.0.0 Packages could already be used for PHP72u? (https://github.com/iuscommunity-pkg/php72u/issues/4)

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
IUS packages are designed to work with stock libraries whenever possible.  Since PHP's GD still works with stock libwebp, I'm inclined to keep using it.  Introducing such a package could also get a bit complicated if a user wants to install both php72u-gd built against libwebp1u and another package that is built against stock libwebp.  A parallel libwebp1 package in EPEL would be a better approach.
