### ISSUE TITLE
XHProf for PHP 5.6+ on RHEL 6+

### ISSUE THREAD

**Issue by shnout** [iuscommunity/wishlist#21]
Please add packages for "XHProf: A Hierarchical Profiler for PHP" from https://pecl.php.net/package/xhprof to the IUS repository.  The packages need to be for PHP 5.6 and PHP 7.0 on RHEL 6 AMD64 and RHEL 7 AMD64.

**Comment by remicollet** [comment]
Notice this extension is unmaintained and ton of forks exists (mostly because of Facebook and its CLA).

**Comment by carlwgeorge** [comment]
Hello @shnout,

We evaluate every request on a case by case basis.  We first ask ourselves if the request is a good fit for IUS.  IUS literally stands for "**I**nline with **U**pstream **S**table".  All the releases of this extension are labelled as "beta".  To @remicollet's point, it hasn't had a release of any kind in over two years.  Until the project has a stable release, I do not feel it is a good fit to be packaged in IUS.

**Comment by shnout** [comment]
I notice that you package the other popular PHP profiler Xdebug at <https://dl.iuscommunity.org/pub/ius/stable/Redhat/7/x86_64/php56u-pecl-xdebug-2.3.3-1.ius.el7.x86_64.rpm>.  Is that the PHP profiler of choice?  I am curious because I support several Moodle LMS instances and the developers have a preference for XHProf per the instructions at <https://docs.moodle.org/dev/Profiling_PHP> and <https://docs.moodle.org/dev/Setting_up_xhprof_on_Moodle>, but it is probable that they would agree to another profiler given that it meets their requirements.  For the last few years, I have packaged XHProf as an RPM package and I have internally deployed it.  EPEL actually packages XHProf at <https://dl.fedoraproject.org/pub/epel/7/x86_64/x/xhprof-0.9.4-2.el7.noarch.rpm>, but that version of XHProf is built for an older version of PHP, thus I have avoided it.  Debian also supports XHProf at <https://packages.debian.org/jessie/php5-xhprof>, but I run RHEL on my supported systems.  Because of its inclusion into the Debian and EPEL repositories, I did not consider that the PECL version was unstable despite the fact that its state was listed as beta.  Part of the reason for the request was that I supposed that other administrators faced a similar situation and therefore the request might address a worthwhile proportion of the administrators that utilize the IUS repository.  Even if it is time to utilize another PHP profiler, I thank you for reviewing my request.

**Comment by b-harper** [comment]
Hey @shnout,

Personally, I am not a PHP developer, so I can't directly answer your question regarding the merits of Xdebug vs XHProf.  Historically, IUS has more chatter around Xdebug then XHProf, but I am not sure if that represents the greater PHP community.  

In the past, IUS has made exceptions with beta quality pecl modules.  The APC module was one of those exceptions,  and we got [burned][0].  Since then, we have been more cautious with beta quality software.   With XHProf, not only is the software considered beta quality from developers, but also appears to be abandonware.  

In regards to Moodle, their documentation does include instructions for profiling with Xdebug.  The time stamp of their documentation is around the time when XHProf was still seeing updates.  I would speculate that Moodle, EPEL and Debian created their packages and/or documentation around the time when it was being developed and I am not sure if they would do the same with XHProf's current state. 

-Ben 

[0]: https://bugs.launchpad.net/ius/+bug/1115670

**Comment by jeffsheltren** [comment]
+1 on including xhprof, I encounter a lot of developers that prefer to use it, and having it in IUS would be very useful.

**Comment by carlwgeorge** [comment]
For those following this request, [this comment](https://github.com/phacility/xhprof/issues/85#issuecomment-196489773) helps to clarify the multiple issues at play here.

**Comment by b-harper** [comment]
I am clearing out stale issues and closing them.  If this issue gets updated, we can open it again.
