### ISSUE TITLE
Redis 5.0.0

### ISSUE THREAD

**Issue by wiza** [iuscommunity/wishlist#211]
### What new package do you want?

Redis 5.0.0

### Why?

Redis 5.0.0 is the newest and greatest :)

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
@wiza Thanks for requesting this.  It would be a logical addition to IUS since we have previously packaged other versions of Redis.

@antirez I'd like your input on this.  For context, IUS is an RPM repo that packages redis.  The packages are designed to stick with the upstream branches, so possibly disruptive changes are always an explicit admin decision rather than an automatic upgrade.  Previously we've packaged:

- redis28u (2.8)
- redis30u (3.0)
- redis32u (3.2)
- redis40u (4.0)

I noticed the next branch is 5.0.  Are you just doing major versions now?  If so I'll create a redis5u package, but if there is any chance of a 5.1 branch one day I'll go with redis50u so that it will always track the 5.0 branch.

**Comment by wiza** [comment]
https://twitter.com/antirez/status/1001480569442783240?lang=en

redis5u seems to be pretty safe bet?

**Comment by evitalis** [comment]
@carlwgeorge I had some time today and gave packaging this a try using Fedora sources per IUS. Let me know what you think. Seemed to build, install, and run fine on CentOS 7.

https://github.com/evitalis/redis50u

**Note** Redis changed the configuration directives for replication from slave* to replica* in redis.conf. So for those updating they may need to review this.

**Comment by wiza** [comment]
5.0.2 is out.

**Comment by evitalis** [comment]
@wiza My update does cover 5.0.2 and is still pending review.

**Comment by carlwgeorge** [comment]
Thanks @evitalis for your work to create the initial spec file.  In addition to helping create the package, working through it with you helped me document IUS packaging.

* https://github.com/iuscommunity/packaging/wiki/guidelines
* https://github.com/iuscommunity/packaging/wiki/walkthrough

I updated the spec file to the latest 5.0.3 upstream release.  [redis5-5.0.3-1](https://github.com/iuscommunity-pkg/redis5/releases/tag/5.0.3-1) will move to the testing repos during tonight's automation, after which point it can be installed by running `yum --enablerepo ius-testing install redis5`.

**Comment by carlwgeorge** [comment]
> I agree to test the new package to ensure that it works as expected. Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

@wiza Have you had a chance to test the redis5 package yet?

**Comment by wiza** [comment]
Sorry, missed your last comment about the package (it wasn't there when I last commented). Just returning to work from 2 weeks of christmas/new year vacation so will test it once all fires have been put out :)

**Comment by wiza** [comment]
We have ran tests to it and seems to work ok. We replaced few 3.2 instances with it.

**Comment by carlwgeorge** [comment]
Thanks for confirming @wiza.  redis5 will move to the stable repos during tonight's automation.
