### ISSUE TITLE
OpenJDK

### ISSUE THREAD

**Issue by kemra102** [iuscommunity/wishlist#213]
### What new package do you want?

OpenJDK 10.x
OpenJDK 11.x

### Why?

At the current pace of Java language development having access to newer versions of the OpenJDK would allow our developers make use of those advancements far sooner than waiting for a new EL release would normally allow.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Please limit wishlist requests to one package per request.

I don't know much about the Java ecosystem.  It appears that RHEL 7 ships JDK6, JDK7, and JDK8 as separate packages that use the alternatives system to set up common paths.  Fedora has JDK8, JDK10, and JDK11.  As of Fedora 28 their [plan](https://fedoraproject.org/wiki/Changes/java-openjdk-10) is to have a single unversioned java-openjdk package that tracks the short term releases, and versioned package names (e.g. java-11-openjdk) for the long term releases.  I found a [document](https://jvanek.fedorapeople.org/devconf/2018/changesInjavaReleaseProcess.pdf) from a Red Hat employee that states JDK11 should eventually be available in RHEL 7 (page 19).

Since JDK10 was a short term release, it is already EOL.

Since java-11-openjdk isn't currently in RHEL, I believe it's eligible for EPEL.  You should [open a bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-11-openjdk) and ask the Fedora maintainer to branch and build for EPEL.  This would of course be removed from EPEL if java-11-openjdk is officially added to RHEL 7.
