### ISSUE TITLE
Add python35u-pip

### ISSUE THREAD

**Issue by stevemowbray** [iuscommunity/wishlist#24]
Please add pip for python35u - it's there for your other python releases.

**Comment by b-harper** [comment]
Hey @stevemowbray,

Thanks for the request.  We use the following to help evaluate a new package request:

Is the new package a good fit for IUS?
Will the new package be maintainable with our current resources?
Is the requester willing to test the new package to ensure expected behaviour?

A python35u-pip package would bee a good fir for IUS and wold be maintainable.  Would you be willing to test this package once we get it into the test repositories?

**Comment by stevemowbray** [comment]
Yes, I would be willing to test it, thanks.

**Comment by b-harper** [comment]
Good to hear.  We will try to get some packages into the testing repositories soon.

**Comment by carlwgeorge** [comment]
@stevemowbray I have completed initial builds of python35u-pip and python35u-setuptools (a dependency of pip).  They will move to the testing repositories during tonight's automation.  Let us know how they work for you.

https://ius.io/Usage/#using-testing-repositories

**Comment by stevemowbray** [comment]
I have installed the testing RPMs on CentOS 6 and CentOS 7 and tested them by installing and uninstalling the various python packages we use. On both OSes it works as expected and installs working packages in the correct site-packages location.

**Comment by carlwgeorge** [comment]
Thanks for the feedback @stevemowbray.  The packages will move to the stable repositories during tonight's automation.
