### ISSUE TITLE
libicu

### ISSUE THREAD

**Issue by kynx** [iuscommunity/wishlist#257]
**What new package do you want?**

`>= libicu-64`

**Why?**

The version that currently ships with RHEL7 (libicu-50) is out-of-date. ICU CLDR data - containing currency formatting rules, timezone information, country names and more - is updated as rules change. The current version uses CLDR data from 2012.

In my particular case, the number of decimal places used when formatting the HUF currency has been fixed in more recent versions, along with a [bug](https://unicode-org.atlassian.net/browse/ICU-10997) setting `FRACTION_DIGITS`. However there are many other updates to formatting rules that others would benefit from.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for submitting this request, sorry the delayed response.

Packages that contain both utilities and libraries can be tricky.  Libraries need to be parallel-installable with the stock equivalent in order to allow other stock packages that link against the stock library to still be installed.  Do you just need the library?  If so, EPEL may be a better path for this.  Fedora already has a [libicu65](https://src.fedoraproject.org/rpms/libicu65) package that could be branched for epel7.  If you also need the CLI utilities or the devel headers, we can look at creating a hybrid package similar to [mariadb102](https://github.com/iusrepo/mariadb102/wiki) where icu65 and libicu65-devel are [safe replacement](https://github.com/iusrepo/packaging/wiki/Guidelines#safe-replacement) packages, but libicu65 is parallel-installable.

**Comment by kynx** [comment]
Yeah fine, I’ve switched to remi who is working on it.
