### ISSUE TITLE
OSSEC RPMs Needed

### ISSUE THREAD

**Issue by vasillalov** [iuscommunity/wishlist#26]
Please build and include OSSEC packages in the IUS repository. At present the only vendor that contributes OSSEC rpms is Atomic. Unfortunately, Atomic repositories create massive conflicts. We would like to maintain full compatibility with IUS without having to use Atomic.

OSSEC can be found here:
http://ossec.github.io/downloads.html

Thank you for your consideration.

**Comment by b-harper** [comment]
Hello @vasillalov,

Thanks for taking the time to submit this request.  With new package request, we use the following questions to help to help evaluate the request:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behaviour?

OSSEC would not be a good fit for IUS as it is not part of EL.  IUS is geared to [providing updated packages][0] that are apart of EL, not for [new packages][1].  EPEL would be the appropriate repository for OSSEC.

-Ben
[0]: https://ius.io/FAQs/#what-is-the-ius-community-project
[1]: https://ius.io/FAQs/#what-is-it-not
