### ISSUE TITLE
sqlite 3.21.x

### ISSUE THREAD

**Issue by arsi** [iuscommunity/wishlist#262]
sqlite

sqlite 3.21.x

sqlite 3.20 and forward support UPSERTs (https://www.sqlite.org/lang_UPSERT.html). RHEL 7 has only sqlite 3.7. sqlite is popular specially with Python.

You are not able to find sqlite from other repositories.

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for the request @arsi.  Unfortunately I don't believe this is something IUS can take on.  The latest sqlite in Fedora (3.31.1) still provides `libsqlite3.so.0`, which is the same library soname as the version in EL7 (3.7.17).  If it were newer we could create a parallel installable library package without disturbing the stock version.  Since we can't, we would have to completely replace the system version of sqlite, and that is far too dangerous for such a low level system component.  My recommendation in this case would be to migrate to EL8 (3.26.0) as soon as you're able in order to get the UPSERT feature.
