### ISSUE TITLE
php71u-pecl-imagick

### ISSUE THREAD

**Issue by aolgin** [iuscommunity/wishlist#271]
**What new package do you want?**

php71u-pecl-imagick

**Why?**

It appears that Red Hat has updated their ImageMagick version from `6.7.8` to `6.9.10`, as per [the CentOS Wiki](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.2003?action=show&redirect=Manuals%2FReleaseNotes%2FCentOS7#Known_Issues). This is preventing us from updating packages on our hosts that use `php71u-pecl-imagick`, or installing that package on new hosts, as it can't find the dependencies. If I'm understanding it correctly, the package needs to be rebuilt with CentOS 7.8 support.

```
$> yum install php71u-pecl-imagick
Loaded plugins: fastestmirror, priorities, s3, versionlock
Loading mirror speeds from cached hostfile
 * base: mirror.centos.org
 * epel: fedora.mirror.serversaustralia.com.au
 * extras: mirror.centos.org
 * updates: mirror.centos.org
1 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package php71u-pecl-imagick.x86_64 0:3.4.3-2.ius.el7 will be installed
--> Processing Dependency: libMagickWand.so.5()(64bit) for package: php71u-pecl-imagick-3.4.3-2.ius.el7.x86_64
--> Processing Dependency: libMagickCore.so.5()(64bit) for package: php71u-pecl-imagick-3.4.3-2.ius.el7.x86_64
--> Finished Dependency Resolution
Error: Package: php71u-pecl-imagick-3.4.3-2.ius.el7.x86_64 (ius-archive)
           Requires: libMagickCore.so.5()(64bit)
Error: Package: php71u-pecl-imagick-3.4.3-2.ius.el7.x86_64 (ius-archive)
           Requires: libMagickWand.so.5()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
This happens regardless of whether I have `ImageMagick` and `ImageMagick-devel` already installed on the server.

I apologize if this is the wrong place to report/ask for this. I saw https://github.com/iusrepo/wishlist/issues/110, and I looked in https://github.com/iusrepo/ and didn't see a repo specifically for this package, so I figured this would be a good place to start.

As it stands, being unable to install (on new servers) or update (on existing servers) `php71u-pecl-imagick` and `ImageMagick` is preventing us from applying updates and properly provisioning new servers. It's possibly also blocking us from even upgrading from Centos 7.7 to CentOS 7.8.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
> Error: Package: php71u-pecl-imagick-3.4.3-2.ius.el7.x86_64 (ius-archive)

See that **ius-archive** part?  The php71u-pecl-imagick package is no longer maintained because PHP 7.1 is EOL upstream.  All php71u packages were retired [last month](https://github.com/iusrepo/announce/issues/16).  The ius-archive repository is disabled by default, so by enabling that on your system you are agreeing to use unmaintained packages.  IUS is not going to rebuild the package to work on CentOS 7.8.  You're free to do this yourself with the [final SRPM we published](https://repo.ius.io/archive/7/src/packages/p/php71u-pecl-imagick-3.4.3-2.ius.el7.src.rpm).

I also would like to note that this repository is used for requesting *new* packages, not for submitting issues for existing packages.  This is laid out clearly in the [contributing guide](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md) of this repository:

>  If you need to report an issue or request an update for an existing package, file an issue on that repository, not here.

If you followed that, you would have seen that the [php71u-pecl-imagick GitHub repository](https://github.com/iuscommunity-pkg/php71u-pecl-imagick) is also marked as archived.
