### ISSUE TITLE
php56u-pecl-imagick

### ISSUE THREAD

**Issue by aolgin** [iuscommunity/wishlist#272]
**What new package do you want?**

php56u-pecl-imagick

**Why?**

It appears that Red Hat has updated their ImageMagick version from `6.7.8` to `6.9.10`, as per [the CentOS Wiki](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.2003?action=show&redirect=Manuals%2FReleaseNotes%2FCentOS7#Known_Issues). This is preventing us from updating packages on our hosts that use `php56u-pecl-imagick`, or installing that package on new hosts, as it can't find the dependencies. If I'm understanding it correctly, the package needs to be rebuilt with CentOS 7.8 support.

```
Error: Package: php56u-pecl-imagick-3.4.3-1.ius.el7.x86_64 (ius-archive)
           Requires: libMagickCore.so.5()(64bit)
           Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@base)
               libMagickCore.so.5()(64bit)
           Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (base)
               Not found
Error: Package: php56u-pecl-imagick-3.4.3-1.ius.el7.x86_64 (ius-archive)
           Requires: libMagickWand.so.5()(64bit)
           Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@base)
               libMagickWand.so.5()(64bit)
           Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (base)
               Not found
Error: Package: php56u-pecl-imagick-3.4.3-1.ius.centos7.x86_64 (@ius)
           Requires: libMagickCore.so.5()(64bit)
           Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@base)
               libMagickCore.so.5()(64bit)
           Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (base)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
This happens regardless of whether I have `ImageMagick` and `ImageMagick-devel` already installed on the server.

I apologize if this is the wrong place to report/ask for this. I looked in https://github.com/iusrepo/ and didn't see a repo specifically for this package, so I figured this would be a good place to start.

As it stands, being unable to update `php56u-pecl-imagick` and `ImageMagick` is preventing us from applying updates. It's possibly also blocking us from even upgrading from Centos 7.7 to CentOS 7.8.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
> Error: Package: php56u-pecl-imagick-3.4.3-1.ius.el7.x86_64 (ius-archive)

See that **ius-archive** part?  The php56u-pecl-imagick package is no longer maintained because PHP 5.6 is EOL upstream.  All php56u packages were retired [over a year ago](https://github.com/iusrepo/announce/issues/12).  The ius-archive repository is disabled by default, so by enabling that on your system you are agreeing to use unmaintained packages.  IUS is not going to rebuild the package to work on CentOS 7.8.  You're free to do this yourself with the [final SRPM we published](https://repo.ius.io/archive/7/src/packages/p/php56u-pecl-imagick-3.4.3-1.ius.el7.src.rpm).

I also would like to note that this repository is used for requesting *new* packages, not for submitting issues for existing packages.  This is laid out clearly in the [contributing guide](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md) of this repository:

>  If you need to report an issue or request an update for an existing package, file an issue on that repository, not here.

If you followed that, you would have seen that the [php56u-pecl-imagick GitHub repository](https://github.com/iuscommunity-pkg/php56u-pecl-imagick) is also marked as archived.
