### ISSUE TITLE
unbound

### ISSUE THREAD

**Issue by drawks** [iuscommunity/wishlist#279]
**What new package do you want?**

unbound 1.10.1

**Why?**

unbound 1.10.1 is 4 point releases ahead of the current centos-7 build of unbound and 6 point releases ahead of the centos-6 version. It includes at least one CVE fix that redhat has acknowdledged and declined to patch in the centos-6 version of unbound (which is supported through the November 2020)

Additionally it includes
* behavioral changes to comply with "flag day" 2019
* support for RPZ (Reply Policy for Zones)
* extended features and extensibility in the python module
* stable sorting of imported configs
* support for ipsets
* support for zone transfers over TLS

This would be a great candidate for IUS especially because it is a drop in upgrade compatible with configuration all the way back to the 1.4.x series, it includes a ton of feature improvements that allow for much greater configuration flexibility AND patches a critical CVE that can lead to existing centos6 machines to be used in DNS amplification attacks.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for the suggestion.  This sounds like it could be a good candidate for IUS.

Do you know what the upstream maintenance policy is?  What do they consider a "branch" or "major version"?  Some projects treat the first segment of their version as a major version ([semantic versioning](https://semver.org)), but others consider the first and second segment of their version as a maintained branch.  That will influence what the package is named.  If a vulnerability was discovered in unbound right now would they release a new 1.9.x version with the fix, or would it only be fixed in 1.10.x?  Depending on their policy I could see the package being named either unbound1 or unbound110.  I checked their website and GitHub but couldn't find any information regarding this.

Just curious, which CVE fix are you referring to that Red Hat declined to fix?

**Comment by drawks** [comment]
> Do you know what the upstream maintenance policy is? What do they consider a "branch" or "major version"? Some projects treat the first segment of their version as a major version (semantic versioning), but others consider the first and second segment of their version as a maintained branch. That will influence what the package is named. If a vulnerability was discovered in unbound right now would they release a new 1.9.x version with the fix, or would it only be fixed in 1.10.x? Depending on their policy I could see the package being named either unbound1 or unbound110. I checked their website and GitHub but couldn't find any information regarding this.

I don't see anywhere that they've officially declared a maint/release policy, but their release history shows no advertised breaking changes in a point release and mainly bug fixes and security patches in patch releases. They cut versions from their master branch and leave it as an exercise to various distro packagers to choose if they'd like to backport patches as they see fit.

> Just curious, which CVE fix are you referring to that Red Hat declined to fix?
[CVE-2020-12662](https://access.redhat.com/security/cve/cve-2020-12662)

Also, I've gone ahead and given a shot at building the latest release against centos-6 and centos-7 (plus epel) using some of the IUS cirrus.ci files as an example and it seems to build the binaries, libraries, python module, debug package and devel package without issue on both platforms; although I haven't yet gone through the excersize of adding in the service unit/initscript and/or updated the scriptlets to handle el6/7 differences conditionally. If the IUS project provides guidance documentation on how these are best handled I'd be happy to make a first pass at this entire effort and then hand it off.

Thanks for your quick response.

**Comment by drawks** [comment]
https://github.com/drawks/unbound < This builds, I think maybe some of the tests need to be modified to pass under the constraints of the cirrus ci build environment.

**Comment by carlwgeorge** [comment]
A small point of clarification from the FAQ at the bottom of that CVE page:

> "Affected" means that our Analysis Team has determined that this product is affected by this vulnerability and might release a fix to address this in the near future.

If Red Hat had declined to fix it, it would be marked as "Will not fix".  Considering how late EL6 is in it's lifecycle (only 5 more months), it is entirely possible it won't get fixed, so this distinction may not matter.

Thanks for taking a look at what will be needed to get an IUS build accomplished.  We actually do have documentation for this process.  First, I'd recommend reading over our [Package Guidelines](https://github.com/iusrepo/packaging/wiki/Guidelines) to get a high level overview of how IUS packages work.  Our [Packaging Walkthrough](https://github.com/iusrepo/packaging/wiki/Walkthrough) contains a step by step guide for creating an IUS repository from the Fedora equivalent (required to preserve the Fedora commit history).  For local test builds you can use our [mock configs](https://github.com/iusrepo/packaging/wiki/Mock).  You can get more details about how to configure the Cirrus build on the [build process](https://github.com/iusrepo/infrastructure/wiki/Build-Process) page.

Circling back to the EL6 lifecycle, since it will be EOL soon I'd rather not add new IUS packages for it.  Targeting this solely at EL7 would simplify the porting process from Fedora, since we'll be able to leave out the sysvinit stuff.  Would you like to take a stab at this following the guide?

**Comment by drawks** [comment]
> Circling back to the EL6 lifecycle, since it will be EOL soon I'd rather not add new IUS packages for it. Targeting this solely at EL7 would simplify the porting process from Fedora, since we'll be able to leave out the sysvinit stuff.

Adding support for both is no major problem and I need to target some EL6 machines for my own use case, so would like to see both supported if at all possible.

> Would you like to take a stab at this following the guide?

[I've run through your walkthrough guide and handled the EL7 packaging with only a few changes.](https://github.com/drawks/unbound1) The one bit that I'm not sure how best to resolve is that the fedora upstream (as well as existing el6 and el7 packages) ship an `unbound-libs` package which is needed at a lower ABI for a handful of existing packages which link against it (`gnutls-dane` for example) AND this `unbound-libs` package additionally ships a a handful of dnssec root anchors and systemd units for managing same. I /think/ it probably makes sense to leave out this extra crypto material and units from our new `unbound1-libs` and either put it in it's own package which would conflict with `unbound-libs` OR make `unbound1-libs` depend on `unbound-libs` which would not conflict with the shared libraries (different sonames, different paths) and would provide this little bit of utility for updating root trust anchors.

At any rate, if you've any guidance for how best to handle this situation I'd be more than happy to tweak the spec file as needed.

**Comment by drawks** [comment]
[FWIW I just finished a branch that adds all the necessary conditionals for sysV on centos-6](https://github.com/drawks/unbound1/compare/centos_6) I'm just now doing some basic testing to make sure I didn't miss anything.

**Comment by drawks** [comment]
@carlwgeorge don't suppose you've had a chance to look at the work I've done so far? I've been doing some testing of these packages for about a week now and so far they seem to work as intended AFAICT.

**Comment by carlwgeorge** [comment]
> The one bit that I'm not sure how best to resolve is that the fedora upstream (as well as existing el6 and el7 packages) ship an unbound-libs package which is needed at a lower ABI for a handful of existing packages which link against it (gnutls-dane for example) AND this unbound-libs package additionally ships a a handful of dnssec root anchors and systemd units for managing same. I /think/ it probably makes sense to leave out this extra crypto material and units from our new unbound1-libs and either put it in it's own package which would conflict with unbound-libs OR make unbound1-libs depend on unbound-libs which would not conflict with the shared libraries (different sonames, different paths) and would provide this little bit of utility for updating root trust anchors.

We have a similar situation with our mariadb102 (and mariadb103) package.  mariadb102-libs is parallel-installable with stock mariadb-libs to allow other applications that link against libmysqlclient.so.18 to still be installed.  The wrinkle we faced with that one was that stock mariadb-libs also contained /etc/my.cnf, so in that case we had mariadb102-libs require mariadb-libs (the file was basically identical in both so it worked).  It was made easier because the spec file already had conditionals to disable the config file to share it from another package (part of the mariadb/mysql setup in Fedora).  More details about the mariadb102 setup are [here](https://github.com/iusrepo/mariadb102/wiki).

If the non-library files in the stock unbound-libs are compatible with the latest version of unbound, then I think a similar approach will work well.

**Comment by drawks** [comment]
That sounds similar to what I did, except I factored out the part I didn't include in my unbound1 packages into it's own package. You haven't indicated whether you've looked at the work I've already done. It has been working well for my purposes for about 6 weeks now.

**Comment by carlwgeorge** [comment]
I took a look over your spec file, good work so far.  I've got a few questions/comments/suggestions, but to proceed in the most efficient way possible, I'd like to do it as an actual GitHub pull request review.  I've created [iusrepo/unbound1](https://github.com/iusrepo/unbound1) from the same Fedora commit you started with.  Please submit your porting work there as a pull request.  I invited you as a member of the [iusrepo organization](https://github.com/iusrepo), so you should be able to push to a feature branch on iusrepo/unbound1 and then open the pull request.

FYI, RHEL has patched [CVE-2020-12662](https://access.redhat.com/security/cve/cve-2020-12662) (the CVE you mentioned in the first comment) across RHEL [6](https://access.redhat.com/errata/RHSA-2020:2640), [7](https://access.redhat.com/errata/RHSA-2020:2414), and [8](https://access.redhat.com/errata/RHSA-2020:2416).

**Comment by carlwgeorge** [comment]
Closing due to lack of feedback.
