### ISSUE TITLE
haproxy dataplaneapi

### ISSUE THREAD

**Issue by hoerup** [iuscommunity/wishlist#285]
**What new package do you want?**

haproxy dataplaneapi

**Why?**

haproxy dataplane api (https://github.com/haproxytech/dataplaneapi ) adds a rest API to haproxy for dynamic configuration of haproxy

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Thanks for opening this package request.  I think you may have overlooked this comment from the issue template.

> IUS is not a generic RPM repository.  It has the limited scope of providing newer versions of packages already in RHEL.  If the software you want is NOT presently available in RHEL, then it is eligible to be added to the EPEL repository, and is out of scope for IUS.

Since this software is not in RHEL, it is out of scope for IUS.  Regarding adding it to EPEL, it has already been packaged in Fedora as [golang-github-haproxytech-dataplaneapi](https://src.fedoraproject.org/rpms/golang-github-haproxytech-dataplaneapi), so I suggest [opening a bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=golang-github-haproxytech-dataplaneapi) to request the maintainer build it for EPEL 7.  It may not be possible until golang in EPEL 7 is updated to 1.14 (currently 1.13.14), because that is what the upstream says is required to build it.
