### ISSUE TITLE
Redis 6

### ISSUE THREAD

**Issue by markroland** [iuscommunity/wishlist#290]
**What new package do you want?**

redis 6

**Why?**

It is the latest version. I've searched and can't seem to find any reason that this package doesn't already exist even though Redis 6 has been out since April 2020

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

^ I'll do what I can although I've never tested a package before.

**Comment by karljohns0n** [comment]
We will also need phpredis > 5.3.0 for redis 6.

**Comment by carlwgeorge** [comment]
> It is the latest version.

I don't have a problem creating a redis6 package, but this alone is not a valid reason.  What does redis 6.x have that redis 5.x doesn't?

**Comment by karljohns0n** [comment]
I haven't tested it yet but this sounds interesting:

> With I/O threading enabled, the new version of Redis can serve up to twice as many operations as before on a single instance, say creators

**Comment by markroland** [comment]
I try to keep our software up-to-date as much as possible as a best practice for security and performance - both of which are included in this release - https://redislabs.com/blog/diving-into-redis-6/.

I've never built a package so I don't entirely know how much work I am asking for here, so if this is excessive and there's little demand then I would agree this doesn't need to be a top priority.

Thanks for the consideration

**Comment by brokenjacobs** [comment]
6.2 releasing soon

**Comment by jdratlif** [comment]
I would like to have redis6 package because version 6 now supports SSL natively, so I don't have to rely on stunnel or some other mechanism for SSL on top of redis. stunnel has caused us a lot of problems in the past, so getting rid of it would be a big benefit to our environment.

https://redis.io/topics/encryption
https://raw.githubusercontent.com/antirez/redis/6.0/00-RELEASENOTES
`Redis now supports SSL on all channels.`

**Comment by vasillalov** [comment]
I would like to have redis 6 package as well. There are several enterprise grade platforms that require Redis 6. This is not about just feature differences between redis 5 and redis 6. This is about support and maintenance of enterprise platforms.

The argument for SSL support in redis 6 is also very valid! This is the primary reason why some platforms are now requiring redis 6 as well!

As a Director of Devops, I value highly long term support and seamless operations. We have based our agency operations around IUS package repositories as they have always been stable, performent and secure. 

My request for redis 6 is driven from the standpoint of software compatibility matrix from the manufacturers of enterprise software.

**Comment by jeffsheltren** [comment]
Happy to have this package in IUS if someone can step up and maintain it.

**Comment by sumitgarg44** [comment]
@jeffsheltren @carlwgeorge 
Trying to add some value though a bit late.

First of all thank you for the walkthrough article which helped me to port redis6 from Fedora to IUS.

I uploaded everything on my personal temp repository https://github.com/sumitgarg44/redis6.git because I think, I won't be able to create redis6 repo under IUS (also shouldn't create until someone review it first).

Will be glad to have a review and move it further.

Build status
=============
- Performed mock build successfully with CentOS-7-x86_64 and epel-7-x86_64.


Installation & other basic tests status
===========================================
- Installed successfully on CentOS7. Even successfully installed devel, doc & debuginfo packages. [1]
     ** redis & sentinel services started successfully. [2]
     ** redis-server & cli version match with installed redis version. [3]
     ** able to stop redis & sentinel services successfully. [4]
     ** redis-cli ping pong worked. [5]

- Uninstalled successfully without breaking anything. Uninstallation saving modified config files with <file name>.rpmsave. [6]

- Installed EPEL stock version and then installation attempt of redis6 failed with conflict. [7]

- Installed redis6 and then installation attempt of EPEL redis failed with conflict. [8]


Artifacts
=============
[1]
$ yum localinstall redis6-d*
Loaded plugins: fastestmirror, langpacks
Examining redis6-6.2.6-2.el7.x86_64.rpm: redis6-6.2.6-2.el7.x86_64
Marking redis6-6.2.6-2.el7.x86_64.rpm to be installed
Examining redis6-debuginfo-6.2.6-2.el7.x86_64.rpm: redis6-debuginfo-6.2.6-2.el7.x86_64
Marking redis6-debuginfo-6.2.6-2.el7.x86_64.rpm to be installed
Examining redis6-devel-6.2.6-2.el7.x86_64.rpm: redis6-devel-6.2.6-2.el7.x86_64
Marking redis6-devel-6.2.6-2.el7.x86_64.rpm to be installed
Examining redis6-doc-6.2.6-2.el7.noarch.rpm: redis6-doc-6.2.6-2.el7.noarch
Marking redis6-doc-6.2.6-2.el7.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package redis6.x86_64 0:6.2.6-2.el7 will be installed
---> Package redis6-debuginfo.x86_64 0:6.2.6-2.el7 will be installed
---> Package redis6-devel.x86_64 0:6.2.6-2.el7 will be installed
---> Package redis6-doc.noarch 0:6.2.6-2.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
<truncated>
Installed:
  redis6.x86_64 0:6.2.6-2.el7 redis6-debuginfo.x86_64 0:6.2.6-2.el7                                    redis6-devel.x86_64 0:6.2.6-2.el7                                    redis6-doc.noarch 0:6.2.6-2.el7


[2]
$ systemctl status redis redis-sentinel
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Thu 2022-01-13 19:55:22 UTC; 2min 24s ago
 Main PID: 2401 (redis-server)
   Status: "Ready to accept connections"
   CGroup: /system.slice/redis.service
           └─2401 /usr/bin/redis-server 127.0.0.1:6379

Jan 13 19:55:22 sumi6119 systemd[1]: Starting Redis persistent key-value database...
Jan 13 19:55:22 sumi6119 systemd[1]: Started Redis persistent key-value database.

● redis-sentinel.service - Redis Sentinel
   Loaded: loaded (/usr/lib/systemd/system/redis-sentinel.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis-sentinel.service.d
           └─limit.conf
   Active: active (running) since Thu 2022-01-13 19:55:16 UTC; 2min 30s ago
 Main PID: 2390 (redis-sentinel)
   Status: "Ready to accept connections"
   CGroup: /system.slice/redis-sentinel.service
           └─2390 /usr/bin/redis-sentinel *:26379 [sentinel]

Jan 13 19:55:16 sumi6119 systemd[1]: Starting Redis Sentinel...
Jan 13 19:55:16 sumi6119 systemd[1]: Started Redis Sentinel.


[3]
$ redis-server -v
Redis server v=6.2.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=4a4498db4c6c3093

$ redis-cli -v
redis-cli 6.2.6


[4]
$ systemctl stop redis redis-sentinel

$ ps aux | grep redis
root      2512  0.0  0.0 112780   708 pts/0    R+   19:58   0:00 grep --color=auto redis


[5]
$ redis-cli
127.0.0.1:6379> ping
PONG


[6]
$ yum remove redis6 redis6-debuginfo redis6-devel redis6-doc
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package redis6.x86_64 0:6.2.6-2.el7 will be erased
---> Package redis6-debuginfo.x86_64 0:6.2.6-2.el7 will be erased
---> Package redis6-devel.x86_64 0:6.2.6-2.el7 will be erased
---> Package redis6-doc.noarch 0:6.2.6-2.el7 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

<truncated>

Running transaction
  Erasing    : redis6-doc-6.2.6-2.el7.noarch                                                                                                                                                                   1/4
  Erasing    : redis6-debuginfo-6.2.6-2.el7.x86_64                                                                                                                                                             2/4
  Erasing    : redis6-devel-6.2.6-2.el7.x86_64                                                                                                                                                                 3/4
  Erasing    : redis6-6.2.6-2.el7.x86_64                                                                                                                                                                       4/4
warning: /etc/redis/sentinel.conf saved as /etc/redis/sentinel.conf.rpmsave
  Verifying  : redis6-devel-6.2.6-2.el7.x86_64                                                                                                                                                                 1/4
  Verifying  : redis6-debuginfo-6.2.6-2.el7.x86_64                                                                                                                                                             2/4
  Verifying  : redis6-6.2.6-2.el7.x86_64                                                                                                                                                                       3/4
  Verifying  : redis6-doc-6.2.6-2.el7.noarch                                                                                                                                                                   4/4

Removed:
  redis6.x86_64 0:6.2.6-2.el7                    redis6-debuginfo.x86_64 0:6.2.6-2.el7                    redis6-devel.x86_64 0:6.2.6-2.el7                    redis6-doc.noarch 0:6.2.6-2.el7


[7]
$ yum install redis6-6.2.6-2.el7.x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Examining redis6-6.2.6-2.el7.x86_64.rpm: redis6-6.2.6-2.el7.x86_64
Marking redis6-6.2.6-2.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package redis6.x86_64 0:6.2.6-2.el7 will be installed
--> Processing Conflict: redis6-6.2.6-2.el7.x86_64 conflicts redis < 6.2.6-2.el7
Loading mirror speeds from cached hostfile
No package matched to upgrade: redis6
--> Finished Dependency Resolution
Error: redis6 conflicts with redis-3.2.12-2.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


[8]
$ yum install redis
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package redis.x86_64 0:3.2.12-2.el7 will be installed
--> Processing Conflict: redis6-6.2.6-2.el7.x86_64 conflicts redis < 6.2.6-2.el7
--> Finished Dependency Resolution
Error: redis6 conflicts with redis-3.2.12-2.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by carlwgeorge** [comment]
@sumitgarg44 This looks great!  Thank you for putting in this work and following the [packaging walkthrough](https://github.com/iusrepo/packaging/wiki/Walkthrough), I'm glad you found it useful.  I think the only thing missing is a changelog entry to give yourself credit.

I've set up the https://github.com/iusrepo/redis6 repo with just the commits from Fedora.  If you can submit your [porting commit](https://github.com/sumitgarg44/redis6/commit/77ff003a992e604403cef27445c5be220c0640d8) (with the changelog entry) as a pull request we can verify the CI build is working correctly.

**Comment by sumitgarg44** [comment]
Thank you, @carlwgeorge to review changes. I have submitted PR https://github.com/iusrepo/redis6/pull/1 with change log entry and seems CI build passed successfully. I have tagged the repo also after successful build in CI.

**Comment by carlwgeorge** [comment]
I've published redis6-6.2.6-3.el7.ius to the testing repository.  Please test this package to ensure it works as expected.

**Comment by sumitgarg44** [comment]
Performed following checks with success on CentOS 7.

1. Installed successfully on CentOS7. Even successfully installed devel, doc & debuginfo packages.
    ** redis & sentinel services started successfully. 
    ** redis-server & cli version match with installed redis version. 
    ** able to stop redis & sentinel services successfully. 
    ** redis-cli ping pong worked.

2. Uninstalled successfully without breaking anything. Uninstallation, saving modified config files with .rpmsave.
3. Installed EPEL stock version and then installation attempt of redis6 failed with conflict. Same result for vice-versa operation.
4. Installed redis5 from IUS and then installation attempt of redis6 failed with conflict error. Same result for vice-versa operation.

**Comment by carlwgeorge** [comment]
I've promoted that build to the main repository.  Thanks again for putting in the work to get this done @sumitgarg44!

**Comment by markroland** [comment]
Thank you @carlwgeorge and @sumitgarg44 !
