### ISSUE TITLE
php74-pecl-mongodb

### ISSUE THREAD

**Issue by zrice57** [iuscommunity/wishlist#295]
**What new package do you want?**

php74-pecl-mongodb

**Why?**

This package provides a mongodb client used by many php applications. We're currently using php73-pecl-mongodb and would love to see the php74 version added. 

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by jeffsheltren** [comment]
Hi, thanks for the request. Finally got around to building this -- based off the php73-pecl-mongodb spec -- and updated to the latest stable upstream version.

I see in Fedora this is now built with client side encryption enabled, but since that requires an additional mongo library we don't currently have in EL7 (AFAICS), I haven't added that to the build. Happy to explore that if it's a requirement for anyone.

This package is now at: https://github.com/iusrepo/php74-pecl-mongodb and has been built and pushed to IUS testing. Please test and let me know how it works for you.

**Comment by zrice57** [comment]
Hi Jeff, thank you for doing this!
What is client side encryption? Does that mean the client can't make SSL connections? 
If so, that's definitely a requirement for us.

**Comment by jeffsheltren** [comment]
I think that's what it means, but I'm not super familiar with encryption and mongodb. Please test and if it's unable to connect over SSL, I'll work on building it with that support.

**Comment by jeffsheltren** [comment]
This worked fine in my testing, so I have pushed it to IUS stable. Please open up issues in the php74-pecl-mongodb repo if you have any problems with it.
