### ISSUE TITLE
Is IUS still maintained?

### ISSUE THREAD

**Issue by markroland** [iuscommunity/wishlist#304]
I appreciate the IUS community and as a Rackspace customer have relied on it for many years to provide modern packages for my environment.

However, in tracking 2 package requests (https://github.com/iusrepo/wishlist/issues/294, https://github.com/iusrepo/wishlist/issues/290) over many months with no progress on any of them if seems like the IUS Repo may be an abandoned project.

Over the months I have tried searching Github, the IUS website (https://ius.io/) and social media for any kind of pulse for IUS, but have found none.

Is anyone maintaining this project? Thank you kindly.

**Comment by jeffsheltren** [comment]
Hi @markroland thanks for asking. The tl;dr is: yes, as best we can. But no longer with developer hours from Rackspace -- though they do host the origin servers and CDN for the package repos, which is very appreciated.

I've been maintaining the PHP 7.3. and 7.4 packages to the best of my ability, and try to jump on any critical security updates for other packages within IUS. @carlwgeorge I'll let speak for himself, but I think jumps in on some other packages as he can -- with his limited time now that he's no longer being paid by Rackspace to work on IUS.

To address your specific questions: re #294 PHP 8.0 -- that's something I have interest in, but haven't had time to pick up. If you -- or anyone -- has time and ability to copy/adjust spec files over from Fedora, I'd be happy to review and help get that built in IUS. Otherwise, I'll pick it up as soon as time allows.

Same goes for Redis, but I don't personally use it much, so I'm less motivated to build it on my own. I'm still available for PR review, etc.

**Comment by carlwgeorge** [comment]
Jeff summed it up nicely.  What I'll add is that I question whether Rackspace still cares about IUS, and open source more broadly.

- They have done routine layoffs since about 2015, especially affecting employees whose roles involve open source work.  From 2014 to 2018, they employed two engineers to primarily work on IUS (including myself).  In early 2018 they laid off the other person, leaving me working on IUS by myself.

- Employees whose roles involve open source work have been told to limit their open source work on company time.  I was told by my management in early 2019 that I had to limit my IUS, EPEL, and Fedora work to 25% of my work time or less.

- They have driven away employees, especially those focused on open source, by refusing to give substantial raises and promotions.

- In early 2020, they ended the open source hosting program, didn't tell the projects using the program, and sent them surprise bills.

- I left Rackspace in December 2019.  In early 2020, as the primary contact on the IUS account, I left negative feedback on an NPS survey regarding the end of the open source hosting program.  In retaliation, they threatened to suspend the account and bill back all usage since I quit and send it immediately to collections.  IUS almost disappeared that day.  Thankfully I was able to work out a solution where a current employee was made the primary contact on the account, narrowly avoiding personal financial impact.

It is true that Rackspace still hosts IUS servers, object storage, and covers our CDN costs.  But at this point I suspect that this continuing is less intentional than it is merely an oversight.  If at some point Rackspace cuts off IUS, I won't be the least bit surprised.  Based on my last interaction with them, me posting this may be the catalyst that triggers that outcome.  And if that comes to pass, I won't lose any sleep over it.

I'd like for IUS to keep going for those that find it useful.  But it will require those that find it useful to get involved.  I've routinely added people to the @iusrepo org (up to 19 members now), but so far Jeff is the only routine contributor.  I'd be happy to add you if you're interested.  I've written several guides in our wiki about [creating new packages](https://github.com/iusrepo/packaging/wiki/Walkthrough), our [build system](https://github.com/iusrepo/infrastructure/wiki/Build-Process), our [release process](https://github.com/iusrepo/infrastructure/wiki/Release-Process), and more.  I'm happy to mentor and provide specific packaging guidance.  But as far as working on IUS directly myself, when I think about IUS I get severely demotivated.  The last thing I want to do with my free time is work on IUS.  My advice?  Migrate from el7 to el8, embrace modularity, and participate in EPEL.  IUS is on life support and [the entire project will be ending with el7](https://ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8) anyways when it reaches EOL in 2024.

**Comment by markroland** [comment]
@jeffsheltren @carlwgeorge Thank you for your service to this project over the years, and thank you for your fast and candid responses.

Having been a customer with Rackspace since 2011, I have experienced its decline of "Fanatical Support" over the last four years so I'm not surprised in the least by your experience, but it is still very disappointing to hear. 

As much as I'd like to roll up my sleeves and participate in IUS, I'd be starting from scratch in terms of compiling software. As we plan for our migration to el8 over the next year it will most likely not be in the same hosting environment, so I think setting my eyes on EL8 and EPEL as you said makes the most sense.

Thank you again for everything you've contributed.
