### ISSUE TITLE
mysql 5.7

### ISSUE THREAD

**Issue by b-harper** [iuscommunity/wishlist#35]
Some initial mysql57u packages have hit the testing repos.  Historical, IUS mysql packages have included some fancy [my.cnf][0] files.  We have been rethinking this approach as part of an effort to get more align with upstream.  The current mysql57u packages have [Fedora's community-mysql][1] configuration files which are now located within the mysql57u-config package.  These configuration files are much more [bare bone][2].

Is the stock configuration files and including them within the mysql57u-config package a good approach for IUS?  

[0]: https://github.com/iuscommunity-pkg/mysql56u/blob/master/SOURCES/my-56-terse.cnf
[1]: http://pkgs.fedoraproject.org/cgit/rpms/community-mysql.git/
[2]: https://github.com/iuscommunity-pkg/mysql57u/blob/master/SOURCES/server.cnf.in

**Comment by troyengel** [comment]
The Rackspace team who spearheaded the initial my.cnf files that are part and parcel to IUS were from their DBA team Best Practices for a turnkey implementation with generally well defined performance increasing options. These configs have since been broken out by Rackspace for use on other implementations such as Percona and MariaDB:

* https://github.com/rackerlabs/rs-db-config/

If the IUS packages choose to revert to a more upstream-based set of configurations, the casual user of the IUS MySQL packages will need to implement their own tuning; for example if they were previously using mysql56u with zero config edits and simply ran a yum replacement to mysql57u, all of those performance tuned options would disappear. We would want to devise some method in assisting those casual users (of which I am one) in how to use the above project to get the same behaviour. Logistically, I consider this a feature of IUS as a casual user - I simply yum install, start it and walk away with the general confidence it will perform well out of the box. The max-connections tweak is a great example of something which is frequently tuned, the upstream default is typically way too low for the average internet-facing webapp (PHP with no database connection pool); the IUS tweak to raise those limits help create a turnkey solution.

Technically, the above upgrade example would possibly break the InnoDB log file sizes; if you make a configuration change to this variable, it's required that MySQL be stopped, the old log files deleted (assuming the stop was successful, ergo the logs were flushed into the DB correctly), then started back up for the upgrade process. This might uncover some RPM technical hurdles to accomplish which may be undesirable from the end-user perspective as the default out of the box value for the InnoDB log file sizes is much, much less than the tweaked files designed previously. (not to say it can't be done, just that there are things to worry about which are hard to test for sometimes in the wild)

**Comment by StephenBrown2** [comment]
Just a thought, perhaps the mysql config could be made another package, and set as a dependency to the ius package?

**Comment by carlwgeorge** [comment]
> Technically, the above upgrade example would possibly break the InnoDB log file sizes

That setting is commented out by default in our configs.  Because of that, mysql55 implicitly uses the upstream default of 5MB.  mysql56u and mysql57u implicitly use the upstream default of 48MB.  Uncommented that setting will cause `my.cnf` to be preserved between updates (even going from mysql55 -> mysql56u -> mysql57u) and the new file be created as `my.cnf.rpmnew`.  It is a sysadmin's responsibility to manage their rpmnew files, plain and simple.

More to the point, the Rackspace DBA team has expressed to us that the MySQL 5.7 upstream defaults are now good enough that shipping a custom my.cnf file is no longer considered essential.  Hence why https://github.com/rackerlabs/rs-db-config doesn't have any 5.7 configs.

**Comment by troyengel** [comment]
Let's not nitpick details if I gave an example that isn't a good one, let's stick with what the spirit of what I was trying to convey is held. Argue about the spirit, not the details - this isn't a technical design issue.

**Comment by FancyFane** [comment]
I agree that its the sysadmin's job to maintain the configs but I also like the idea of having a turnkey solution(s) in place. If Rackspace DBAs have absolutely no input on the upstream my.cnf file then I would pass it through as is, however, if there are ANY recommendations from the Rackspace DBAs we should have them included; even if they're commented out. 

While some people have the luxury of being able to able to consult with a MySQL DBA not everyone who uses IUS will have that same ability. By providing notes and comments on certain directives it could save everyone a lot of heartache further down the line.

**Comment by troyengel** [comment]
I tried to cull some data for us -- I spun up generic CentOS7 then downloaded these:

* http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.28-linux-glibc2.5-x86_64.tar.gz
* http://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.10-linux-glibc2.5-x86_64.tar.gz
* https://raw.githubusercontent.com/rackerlabs/rs-db-config/master/mysql/my-5.6-rhel.cnf

I then set up the normal, by the book /usr/local/mysql/ setup for each one, then captured the output of "show global variables" with a little sed action with each set of defaults. I then deployed the custom config file (editing out the paths to data at the top), then generated the data again. I then ran the 5.7 data through diff -u0N to get a clean diff of what applying the custom config will change in 5.7:

````
--- mysql57def.txt	2016-01-15 19:10:47.152069245 -0600
+++ mysql57rsdb.txt	2016-01-15 19:18:46.326883970 -0600
@@ -7 +7 @@
-back_log=80
+back_log=130
@@ -61 +61 @@
-expire_logs_days=0
+expire_logs_days=7
@@ -90 +90 @@
-host_cache_size=279
+host_cache_size=528
@@ -93 +93 @@
-ignore_db_dirs=
+ignore_db_dirs=lost+found
@@ -185 +185 @@
-innodb_open_files=2000
+innodb_open_files=4096
@@ -230 +230 @@
-key_buffer_size=8388608
+key_buffer_size=33554432
@@ -270 +270 @@
-max_allowed_packet=4194304
+max_allowed_packet=16777216
@@ -274,2 +274,2 @@
-max_connect_errors=100
-max_connections=151
+max_connect_errors=1000000
+max_connections=400
@@ -302 +302 @@
-myisam_sort_buffer_size=8388608
+myisam_sort_buffer_size=134217728
@@ -316 +316 @@
-open_files_limit=5000
+open_files_limit=65535
@@ -394 +394 @@
-relay_log_space_limit=0
+relay_log_space_limit=17179869184
@@ -403 +403 @@
-server_id=0
+server_id=1
@@ -415 +415 @@
-skip_name_resolve=OFF
+skip_name_resolve=ON
@@ -466,2 +466,2 @@
-table_definition_cache=1400
-table_open_cache=2000
+table_definition_cache=4096
+table_open_cache=4096
@@ -469 +469 @@
-thread_cache_size=9
+thread_cache_size=12
@@ -488 +488 @@
-wait_timeout=28800
+wait_timeout=600
````

These are the performance customizations that would be lost by dropping the custom config file. Some of them seem rather important to increase default performance, but I am not a professional DBA to provide proper input (but I can guess at some of them - max-connections is easy, thread_cache_size, etc.).

Attaching all files from the show global variables output, we should ask a DBA of some sort to review these changes and comment on the impact of "losing" those customizations when existing users yum update to the new release with default (non-edited) config files.

[mysql56def.txt](https://github.com/iuscommunity/wishlist/files/92734/mysql56def.txt)
[mysql56rsdb.txt](https://github.com/iuscommunity/wishlist/files/92733/mysql56rsdb.txt)
[mysql57def.txt](https://github.com/iuscommunity/wishlist/files/92735/mysql57def.txt)
[mysql57rsdb.txt](https://github.com/iuscommunity/wishlist/files/92736/mysql57rsdb.txt)

**Comment by carlwgeorge** [comment]
Relevant links:

http://mysqlserverteam.com/improved-server-defaults-in-5-7/

http://mysqlserverteam.com/planning-the-defaults-for-mysql-5-8/

**Comment by troyengel** [comment]
Fantastic links/reads, a really good argument for dropping the custom configs. If upstream is taking this seriously now, I'm convinced - let's drop the custom configs and support upstream's efforts to create an out of the box optimized solution. IUS could intrinsically help vet these choices they're making and expose any flaws in the plan.

**Comment by b-harper** [comment]
For anyone wondering why Rackspace keeps getting mentioned, [Rackspace sponsors IUS][0].  Whatever decision is reached, it needs to what is best for all IUS users.

@troyengel, @StephenBrown2 and @FancyFane, thanks for the feedback.  

@StephenBrown2, I don't see how moving the server's configuration file to a required separate package would make a difference.  If a user would go to install mysql57u-server, they would still end up with the same configuration file.  

@FancyFane, I do not think there is one 'turnkey solution' for all the different use cases.  For a default configuration, we just need some sane defaults.  It was only due to lack of sane defaults from upstream that we decided on custom configurations.

I also wanted to clarify how Fedora's community-mysql configuration files are laid out.  Stock EL 6 uses a single configuration file /etc/my.cnf.   Fedora's community-mysql has minimal [/etc/my.cnf][1] with majority of the configuration is within /etc/my.cnf.d/.  The current mysql57u packages are built this same way.  EL 7's mariadb work similarly.   While I like the direction Fedora and EL 7 are taking, I do not think it is a good idea for our mysql57u packages as it is not the excepted behaviour in EL 6.  


[0]: https://ius.io/History/#project-history
[1]: http://pkgs.fedoraproject.org/cgit/rpms/community-mysql.git/tree/my.cnf.in

**Comment by StephenBrown2** [comment]
@b-harper Yes, sane defaults is a good thing. I have noticed previously though that there were several configuration collections given, and I was thinking more of a soft dependency, though I don't know if that's possible with yum, as opposed to dnf. Making ius configs a separate package makes sense to me still, maybe not as a dependency though. If the default config is going to be good, there may be no need to change it. Most people don't.

**Comment by b-harper** [comment]
@StephenBrown2, thanks for the clarification.  It is unfortunate that EL 6 does not have a way to do soft dependencies, as that is a possible solution.  Even if it did, we would need to get creative as two packages that own the same file (unless they are identical) can not be installed at the same time.  

Various MySQL (and clones) packages have provided alternative configuration files within /usr/share.  While I am not crazy about that idea, that is an option we can consider.

**Comment by b-harper** [comment]
FYI, mysql57u-5.7.10 packages will be hitting the testing repo tomorrow.  No changes to the configuration files have been made yet.

**Comment by otteydw** [comment]
@b-harper asked my thoughts in a linked issue.

I like the thought of leaving a stock version of the config file from the upstream as part of the new mysql57u-config package.  Maybe also include a my-tuned.cfg or something similar that someone could use if they desire.  I was surprised to find that the upstream/stock config was not being used or included in the IUS package.

**Comment by b-harper** [comment]
@otteydw, thanks for sharing your thoughts.

Updated mysql57u-5.7.10 have been built to address [this issue][0].  They will hit the testing repositories after tonight's automation run.  


[0]: https://github.com/iuscommunity-pkg/mysql57u/issues/1

**Comment by b-harper** [comment]
So, I think I have changed my mind regarding  the configuration files locations.  

Before,  I thought sticking with a single /etc/my.cnf (like stock EL 6 mysql packages and previous IUS mysql packages) was the best approach.  Fedora's and EL 7 approach of is to use a minimal /etc/my.cnf with majority of the configuration is within /etc/my.cnf.d/.  This might allow for flexibility for IUS to include stock configuration files and give the user  the ability to add custom configuration in other files.  I'll need to do some testing to see if/how that would work.

**Comment by StephenBrown2** [comment]
Can /etc/my.cnf include other files? (I guess it must, since EL 7 is doing it...)

If so, that seems highly logical.

**Comment by b-harper** [comment]
@StephenBrown2, Yes, the includes is everything within /etc/my.cnf.d:

```
$ tail -n 5 /etc/my.cnf
#
# include all files from the config directory
#
!includedir /etc/my.cnf.d
```

**Comment by b-harper** [comment]
Thanks to all who have given feedback.  We are going to proceed and push the packages into the stable repositories during tonight's automation run.
