### ISSUE TITLE
php70u-pecl-mysql

### ISSUE THREAD

**Issue by Cadonline** [iuscommunity/wishlist#39]
Hello,
I know that mysql EXT is removed as of PHP 7. But I guess I'm no the only one with very big legacy Projects which just can't be simply updated to mysqli/PDO. I did some extensive Tests with manual Mysql Module compile fron here: https://github.com/php/pecl-database-mysql and it's working like a charm. It would be great if you could make this Package available within IUS so one would be able to use PHP 7 with old Projects using Mysql EXT.
Thx

**Comment by b-harper** [comment]
Hey @Cadonline,

Thanks for taking the time to file this request.  We uses these questions to help evaluate requests:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behavior?

Unfortunately, this package would not be a good fit for IUS.  Both the [GitHub repository][0] and the  [PECL page][1] make it very clear that this software should no longer be used.  Seeing that it is no longer maintained, we will not including it in our repositories.   


[0]: https://github.com/php/pecl-database-mysql
[1]: https://pecl.php.net/package/mysql

**Comment by remicollet** [comment]
The [php-pecl-mysql](http://rpms.remirepo.net/enterprise/7/php70/x86_64/repoview/php-pecl-mysql.html) should work correctly with **php70u** stack.

As I'm working with upstream, feedback welcome.

**Comment by b-harper** [comment]
Hey @remicollet, can you please confirm the status of this module.  There seems to be clear wording that this module is no longer maintained.  Are there plans to actively maintain this module again?

**Comment by remicollet** [comment]
I confirm it is deprecated and not maintained.

**Comment by Cadonline** [comment]
It's really a shame they ditched ext/mysql from PHP ... I got some old legacy PHP Projects  > 100.000 PHP Files - hundred thousands calls to old Mysql Commands ... would take Ages to upgrade to mysqli/PDO - which Client would never pay ...
As they are hosted on dedicated Root Servers I can compile Mysql Module myself - but others rely on RPMs ... so thx for creating it remicollet! :-)

**Comment by carlwgeorge** [comment]
I just tested @remicollet's solution.  Be forewarned that if you enable the remi-php70 repo to get php-pecl-mysql, it will cause all IUS php70u packages to be replaced by their Remi equivalents, due to his [unnecessary](https://github.com/remicollet/remirepo/blob/73ae327d10032ff6172e7e13cf56add107801fbc/php/php70/php70.spec#L275) [usage](https://github.com/remicollet/remirepo/blob/73ae327d10032ff6172e7e13cf56add107801fbc/php/php70/php70.spec#L331) of [obsoletes](https://github.com/remicollet/remirepo/blob/73ae327d10032ff6172e7e13cf56add107801fbc/php/php70/php70.spec#L396).  There are ways around this, such as manually downloading the RPM or using exclude/includepkgs directives in the repo file; however, I will continue to recommend that users choose either IUS ***or*** Remirepo, but ***not both***.

**Comment by remicollet** [comment]
> manually downloading the RPM

that's the reason why I post the link to the package, not to the repo configuration.

> I will continue to recommend that users choose either IUS or Remirepo, but not both.

I agree.

**Comment by Cadonline** [comment]
@remicollet - when installing the RPM directly - without your Repo - can it happen that php-pecl-mysql stops working sometime when PHP is updated? Or will it stay compatible with all PHP 7 Versions? (Had some custom Modules where I had to phpize/configure/make when PHP Version changed ... so I fear this can happen here too??)
IUS PHP is updated, php-pecl-mysql not - Website = down?

**Comment by remicollet** [comment]
> will it stay compatible with all PHP 7 Versions?

No, only with 7.0.x versions (ABI is only stable between minor release)

**Comment by Cadonline** [comment]
alright - thx for clarification!
I guess @b-harper won't do ABI breaking updates with "yum update" like 7.0.x --> 7.1.x?

**Comment by carlwgeorge** [comment]
IUS packages are tied to the MAJOR.MINOR upstream branch.  php70u will always be PHP 7.0.x, and will never directly `yum update` to 7.1.x.  Thus, within the php70u stack there should never be an ABI breaking update.
