### ISSUE TITLE
php56u-pecl-yaml

### ISSUE THREAD

**Issue by cervajs** [iuscommunity/wishlist#41]
I would like to request for php56u-pecl-yaml to be added to IUS for centos6. I'm willing to test it when it's available

it's available in standard centos6 as php-pecl-yaml

**Comment by b-harper** [comment]
Hey @cervajs,

It was good chatting with you on IRC and thanks for taking the time to submit this request.  We can not promise that we will proceed with every request, so we came up with these questions to help evaluate requests:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behaviour?

This is a good fit for IUS and would be maintainable with our current resources.  Also, you stated that you would test the package.  We will look to get some initial packages built and into the testing repositories soon.  

-Ben

**Comment by b-harper** [comment]
Hey @cervajs,  I was able to squeeze in some time today and some initial packages will be hitting the testing repositories after tonight's automation run.  Please let us know if they are working for your needs.

**Comment by cervajs** [comment]
installation ok

Downloading Packages:
php56u-pecl-yaml-1.2.0-1.centos6.i686.rpm                                                                                              |  28 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : php56u-pecl-yaml-1.2.0-1.centos6.i686                                                                                                      1/1
  Verifying  : php56u-pecl-yaml-1.2.0-1.centos6.i686                                                                                                      1/1

Installed:
  php56u-pecl-yaml.i686 0:1.2.0-1.centos6

phpinfo();
LibYAML Support 	enabled
Module Version 	1.2.0
LibYAML Version 	0.1.3 

web app works like a charm
thank you

**Comment by b-harper** [comment]
Hey @cervajs,

Thanks for the feedback.  These packages will get moved into the stable repos during tonight's automation.
