### ISSUE TITLE
MariaDB Galera packages

### ISSUE THREAD

**Issue by kemra102** [iuscommunity/wishlist#5]
Is it possible to build the Galera packages for the **mariadb100u** package set (Galera is not part of standard MariaDB until 10.1)?

This would allow us to use IUS for Galera clusters across CentOS 6/7. It would be even more useful as last time I tested the packages from the official MariaDB repos for EL7 they did not even come with SystemD unit files like the IUS ones do.

**Comment by b-harper** [comment]
Hey kemra102,

Thanks for taking the time to contact us about this request.  With all new package requests, we evaluate if it would be a good fit for IUS and if it is maintainable with our current resources.  IUS has a narrow focus of only providing new packages that are in RHEL.  For packages not in RHEL, EPEL is appropriate repo.  

Currently, we only package mariadb100u for EL 7, as mariadb is only available for EL 7.  Looking over the EL 7 repos, I do not see any mariadb-galera packages.  From what I can tell, mariadb-galera is not a plug-in for mariadb, but a separate application used instead of mariadb.  (Please correct me if I am wrong). Also given the fact that galera will be part of 10.1, it is not a straight forward answer if this package is a good fit for IUS.  Currently, we are learning toward waiting for 10.1.  

-Ben

**Comment by kemra102** [comment]
If we're going to get 10.1 when stable I'm inclined to agree that's the way to go in this case.

**Comment by b-harper** [comment]
Request for MariaDB 10.1 #20

**Comment by carlwgeorge** [comment]
@kemra102 Let's close this issue and continue the conversation over in #20.  By the way, the initial mariadb101u packages should hit the testing repositories during tonight's automation.  We would love it if you could test and provide feedback.
