### ISSUE TITLE
librabbitmq 0.7.1

### ISSUE THREAD

**Issue by marksteele** [iuscommunity/wishlist#53]
### What package do you want?

librabbitmq 0.7.1
### Why?

The stock 0.5.2 version is now over 2 years old, and a more recent version has been released in October 2015 with numerous improvements.
### OS versions

RHEL/CentOS 7
### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
This one is a bit tricky.

EPEL6 and EPEL7 have version 0.5.2, which provides `librabbitmq.so.1`.  The latest upstream version 0.7.1 provides `librabbitmq.so.4`.  If we do a replacement package, everything that compiles against 0.5.2 would be incompatible.  That includes php-pecl-amqp and php56u-pecl-amqp.  Traditionally IUS has stuck with building against stock and EPEL libraries.  We only diverge from that strategy when the software will no longer build against the stock/EPEL libraries.  We could investigate if it is possible to provide it as a parallel library, but then we still have the problem of which version to compile our pecl-amqp package(s) against.

In order to fully consider the situation, we need more specifics on the differences between 0.5.2 and 0.7.1.  Being two years old is not a good enough reason on it's own.  Is there a specific bug you are trying to work around?  It may be appropriate to ask the EPEL maintainer to backport the specific fixes, or even investigate if rebasing the EPEL packages to the latest version is acceptable within EPEL guidelines.

It looks like @remicollet is the EPEL maintainer.  @remicollet, what are your thought?

**Comment by remicollet** [comment]
Version 0.5.2 is stable, no bug report, and suite the update policy in EPEL.
No reason to update.

IIRC I even fix pecl/amqp to build with this version, so 0.5.2 is still the minimal requirement (even for upcoming 1.7.0)

And I think people wanting the "lastest" should use remirepo ;)
(librabbitmq-last 0.7.1, is available for parallel installation, as php-pecl-amqp for 5.4, 5.5, 5.6 and 7.0, using it)

**Comment by guilhermeblanco** [comment]
@remicollet Most of development efforts of PHP PECL AMQP were done with librabbitmq 0.7.1. Even though package claims to be compatible with 0.5.2, I experienced segfaults such as this one:

```
Jun 14 22:01:53 web01 kernel: php-fpm[2184]: segfault at 7ff1342720c5 ip 00007ff15b5f31eb sp 00007ffe04c70f30 error 4 in php-fpm[7ff15b3a8000+37f000]
```

**Comment by b-harper** [comment]
I am closing out stale issues.  This can be reopened if needed.
