### ISSUE TITLE
geoip

### ISSUE THREAD

**Issue by anthonyneto** [iuscommunity/wishlist#56]
### What package do you want?

geoip
### Why?

Centos 7 base/epel has a version 1.5.0-9.el7, I would like a version > 2 for the geoipupdate bin so I can use the same bin as centos 6, some of the flags have changed.
### OS versions

I would like this package for RHEL 7.
### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @anthonyneto,

Thanks for reaching out with this request.

Small point of clarification, geoipupdate has been broken out into a separate tool with a separate version number.  EPEL6 has GeoIP 1.6.5 and geoipupdate 2.2.1.  Base RHEL7 (not EPEL) has GeoIP 1.5.0, which was prior the geoipupdate being broken out.

I actually have a bugzilla report open with Red Hat to rebase RHEL7's GeoIP in order to get the IPv6 integration from Fedora (which the EPEL6 package has already).  My guess is that the best solution for Red Hat is to rebase the RHEL7 package to match the EPEL6 package, which will take care of both the IPv6 issue and your issue with the geoipupdate flags.  That is just my speculation, but I have been told that Red Hat is planning on addressing the IPv6 issue in RHEL 7.3.  Depending on how that plays out, it won't make sense for IUS to create newer GeoIP/geoipupdate packages.

Unfortunately, my bugzilla report has been marked as private.  I'll see if I can get that changed so you can subscribe and see the progress as well.

**Comment by chasebolt** [comment]
interested in this as well

**Comment by carlwgeorge** [comment]
Good news, I finally got that bugzilla marked as public.  You can now add yourself to the CC list to be notified when it gets updated/resolved.

https://bugzilla.redhat.com/show_bug.cgi?id=1201857

**Comment by b-harper** [comment]
The Red Hat bug has been update and GeoIP will get updated to 1.5.0-11 in RHEL 7.3.  This update will include IPv6 data.  We will reevaluate this request.

**Comment by chasebolt** [comment]
Awesome thanks!

**Comment by b-harper** [comment]
Sorry for the delay in updating this issue.

Looking over the man page and output of ```-h``` for geoipupdate for both EL6 and EL7, there appears to be only a single difference.  The EL6 version includes ```-V``` to display the version that is not included in the EL7 version.  Both contain, ```-d```, ```-f```, ```-h``` and ```-v```.

I wanted to check to see if this package is still needed.

**Comment by b-harper** [comment]
It would appear that this package is no longer needed.  I am going to close this issue.  We can reopen this issue if needed.
