### ISSUE TITLE
python35u-lxml

### ISSUE THREAD

**Issue by mjholtkamp** [iuscommunity/wishlist#59]
### What package do you want?

python35u-lxml

### Why?

Currently, python33u-lxml exists, but we would like to use python 3.5 instead of 3.3.
Python 3.5 has many advantages over 3.3 like async and await, performance
improvements and bug fixes. IUS already has the python35u, so to the best of
my understanding there are no additional dependencies to also create.

### OS versions

I would like this package for at least RHEL 6.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @mjholtkamp,

Thanks for reaching out to us.  I have most of the work done for this package, but the test suite has multiple failures on EL6.  After some investigation, I believe the reason is that EL6 has a problematic version of libxml2.

> If you want to use the feed parser interface, especially when parsing from unicode strings, do not use libxml2 2.7.4 through 2.7.6.

http://lxml.de/installation.html#requirements

EL6 is using libxml2 2.7.6.  All of the test suite failures have some mention of feed parser.  I know that we are already building lxml for EL6 with the python27/32/33 stacks, but apparently the test suite is not enabled, so we didn't catch this problem before.  I am concerned that shipping python35u-lxml on EL6 would mean shipping a broken feed parser interface (not to mention that our existing lxml packages could be partially broken as well).  If the package still has value on EL6 without the feed parser interface, we can skip the test suite there but still run it on EL7.

Are you familiar enough with the feed parser interface to shed any light on the situation?

**Comment by mjholtkamp** [comment]
Hello Carl,

First off, thanks for the work you’ve already put in!

We do indeed use libxml2 2.7.6 with EL6, we also currently run python-lxml (2.2.3-1.1) with python 2.7. Do you know if this problem only surfaces with python 3 or does it also occur with python 2.7? We have not experienced any problems as far as I know.

I do not have intimate knowledge of the feed parser interface, but I did check how we are using it. We are using it through BeautifulSoup4 and it looks like it is definitely using the feed parser interface (in the way we use BeautifulSoup4).

We are not using unicode strings however, so we might just be lucky. At least it’s good to know that these versions might pose problems.

This situation is hard to judge. On the one hand I’m quite concerned about the know problems with the libxml2 versions, on the other hand we do not seem to be hit by it at all. Then again, in python 3 all strings are unicode, so maybe in python3 we will be hit by it.

Is it in any way possible to install a slightly newer version of libxml2 on EL6 so this problem will not occur?

**Comment by carlwgeorge** [comment]
Stock EL6 libxml2 2.7.6 works fine with stock EL6 python-lxml 2.2.3.  That is because lxml 2.2 series only required libxml2 2.6.21.  For IUS we are looking at the latest upstream lxml, currently version 3.6.0, so the requirements are more stringent.

I'm not sure if this is a PY3-only problem.  I'll try running the test suite on our python27-lxml package and see if I can reproduce the issue.  Would you be willing to try out our python33-lxml package in your environment to see if that one works for you?  If python33-lxml works for you, I imagine python35u-lxml would work as well.

We might be able to create a [parallel installable package](https://ius.io/SafeRepo/#parallel-installable-package) of libxml2 that is the latest version that can be installed in parallel with the stock EL6 version.  We would then use conditionals in the lxml spec files to use the parallel package library path on EL6, but the stock path on EL7.  I'll check out if this is even possible.

Another possibility would be to only build this package for EL7, and just skip EL6 entirely.  IUS strives for have consistency with regard to the EL releases we ship our packages on.  In other words, if we ship python35u for EL6 and EL7, then we want ship all our python35u module packages for EL6 and EL7 as well.  However, this consistency sometimes isn't easily achievable.  For example, we ship python27 for EL5 and EL6, but we only ship python27-lxml for EL6.

**Comment by carlwgeorge** [comment]
The test suite fails on python27-lxml on EL6.  The exceptions aren't identical to the ones on python35u-lxml, but they definitely mention the feed parser.

**Comment by carlwgeorge** [comment]
After giving this some thought, I realized that the [upstream website](http://lxml.de/installation.html) explicitly states the actual minimum version of libxml2 is 2.7.0.  libxml2 2.7.6 is mentioned as being problematic, but apparently it isn't bad enough to change the minimum required version to 2.7.7.  Thus, I will only run the test suite on EL7, and skip it on EL6.

I have finished the build and the packages will move to the testing repositories during tonight's automation.

**Comment by mjholtkamp** [comment]
That's great news (kind of!). I was considering the options as well. I was afraid we had to do something else entirely. Let me know if I can start testing.

**Comment by carlwgeorge** [comment]
The python35u-lxml package is available in our testing repositories.  If you are using the ius-release package, you can install it by running this:

    yum --enablerepo ius-testing install python35u-lxml

**Comment by mjholtkamp** [comment]
Thanks! I will take a look today.

**Comment by mjholtkamp** [comment]
Just confirmed that it works. I took a snippet of our code (the code is not fully python3 compatible yet) and executed it successfully.

I did get an error message during pip install lxml when building the wheel, but that was because of an older wheel version (0.24, while 0.29 is the newest atm). The package (lxml) did install succesfully however.

After uninstalling lxml and upgrading the wheel package with pip, I could successfully pip install lxml.

So as far as I'm concerned, this package is a GO.

What are the next steps?

**Comment by b-harper** [comment]
Hey @mjholtkamp,

Any chance you could test the python35u-lxml in the ius-testing repository?

-Ben

**Comment by mjholtkamp** [comment]
Hi Ben,

I'm apologise for being unclear. In my previous comment I tried to say that I tested the python35u-lxml from the ius-testing repository and it works like a charm (after upgrading my 'wheel' package).

So to be perfectly clear, as far as I'm concerned, the package is OK.

**Comment by b-harper** [comment]
Hey @mjholtkamp,

Thanks for the clarification.  This package will get pushed into the stable repositories during tonight's automation.
