### ISSUE TITLE
httpd24u-mod_passenger

### ISSUE THREAD

**Issue by brianb111** [iuscommunity/wishlist#67]
### What package do you want?

mod_passenger.x86_64 : Apache Module for Phusion Passenger built against httpd24u
### Why?

Customer needs mod_passenger  package to load Phusion Passenger as a module into Apache and that is what we need to actually run our application. We are using RoR (ruby on rails) and using Phusion Passenger attached to Apache so that we can manage the restart of the application server with the restart of apache.
### OS versions

I would like this package for both RHEL 6 and 7.
### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by brianb111** [comment]
Repo is Rackspace - RHEL EUS Server (v. 6.7.z for 64-bit x86_64) - IUS

**Comment by carlwgeorge** [comment]
Howdy @brianb111,

This request appears to be pretty complicated.  The mod_passenger module is built as part of the rake build process for passenger itself.  Passenger has a long list of ruby dependencies.  Passenger has their own repository, and it's packages are built against the stock versions of httpd and ruby.  Passenger is available in EPEL for EL7, but not for EL6.  IUS is focused on providing newer versions of stock software, not additional software.  But even if we were to build passenger for EL6 (or a newer version for EL7 than EPEL has available), we would still choose to build it against stock httpd and ruby, for maximum compatibility.

Due to the complexities described above, passenger in IUS would be difficult to maintain.  If the primary goal is to get passenger and httpd 2.4, the best solution would be to use the upstream passenger repository on EL7, which will be built against stock httpd 2.4 already.

**Comment by b-harper** [comment]
I am clearing out stale issues and closing them.  If this issue gets updated, we can open it again.
