### ISSUE TITLE
OpenSSL 1.0.2 for HTTP/2

### ISSUE THREAD

**Issue by ralfbecker** [iuscommunity/wishlist#70]
### What package do you want?

openssl-1.0.2
### Why?

OpenSSL 1.0.2 is required to run Nginx with HTTP/2.
RHEL/CentOS 7 only comes with 1.0.1e and therefore does not allow to use HTTP/2 without compiling an own OpenSSL version.
Fedora 23+ has 1.0.2h: https://apps.fedoraproject.org/packages/openssl
### OS versions

I would like this package for RHEL 7.
### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @ralfbecker,

Thanks for opening a request with us.

We've been down this road before.  RHEL 6 originally launched with openssl 1.0.0.  We received a [request to build a newer version within IUS](https://bugs.launchpad.net/ius/+bug/1034961), which we did under the name openssl10 (initial version 1.0.1c).  It proved to be quite difficult to maintain, and to be honest didn't live up to our own standards of quality.  Later in RHEL 6.5, Red Hat [rebased the stock version of openssl to 1.0.1e](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/6.5_Technical_Notes/index.html#openssl), so [we decided deprecate our openssl10 packages](https://lists.launchpad.net/ius-community/msg00804.html).  Users who decided to switch to openssl10 had to manually switch back to stock openssl to continue getting security fixes.

Attempting to maintain our openssl10 packages taught us that maintaining a critical library package like openssl is quite a bit more difficult than standard applications like PHP and MySQL.  We proceed with that package under the impression that the RHEL 6 openssl package would be stuck at 1.0.0 forever, so having a newer version available would be worth the effort.  Red Hat's eventual rebase of openssl in RHEL 6.5 certainly made us regret the decision.  This time, we actually already know that Red Hat is planning a [rebase for the RHEL 7 openssl package](https://bugzilla.redhat.com/show_bug.cgi?id=1276310) from the current 1.0.1e to 1.0.2.  The bugzilla indicates that this is currently planned for RHEL 7.4.

I think going forward with this request would cause headaches for both package maintenance and user consumption.  That combined with the known short lifecycle makes me lean towards declining this request.

**Comment by stylobille** [comment]
Hello,

Well since readhat seems to be releasing a "minor" version every 8 month or so (7.2 was november 2015), we might have to wait an other year for a 7.4 version (which seems quite a long time to me).

I have no idea how much work this is for you, be currently I'm trying to setup a webserver with http 2.0 enabled and I'm pretty much stucked if I want to go on with Redhat.

I would really appreciate an OpenSSL 1.02 package and would certainly use it if you provide it !

(By the way with what version do you compile your httpd24u version ?)

**Comment by ralfbecker** [comment]
I'm going to reinstall the server now with Ubuntu-16.04, which comes with OpenSSL 1.0.2h and nginx.org has packages for it as well. I don't to compile such a security critical package and make sure it's up do date for about one year. Same is probably true for Carl ;-)

**Comment by carlwgeorge** [comment]
There are various problems with fulfilling this request.

* confusing name

What would be an appropriate name for such a package?  Our typical naming format of `${name}${major}${minor}u` would result in the name openssl102u.  However, OpenSSL includes a letter in their upstream version.  This could confuse users that we have some newer version of OpenSSL than it actually is (openssl102u version 1.0.2h).  The alternative name of openssl10u isn't appropriate because the major upstream branches are 1.0.1, 1.0.2, and so on.

* lifecycle

IUS follows the upstream lifecycle.  This means that if we offer openssl102u, we would be on the hook for maintaining it for the whole 1.0.2 upstream lifecycle (until [2019-12-31](https://www.openssl.org/source/)).  But once RHEL 7.4 comes out, there won't be incentive for users to use our openssl package over the stock one, meaning that at that point we would be maintaining the package for little to no user benefit.  The last time we packaged OpenSSL we broke our policy and deprecated the package early, which caused considerable headaches for our users, because upgrading to and downgrading from IUS packages is a manual process.

* library compatibility

A large amount of the base EL operating system compiles against OpenSSL.  Even though OpenSSL 1.0.1 and 1.0.2 both advertise themselves as providing `libssl.so.10`, there are not [perfectly ABI compatibile](http://abi-laboratory.pro/tracker/timeline/openssl/).  To ensure a stable system, upgrading OpenSSL to 1.0.2 will require rebuilding practically the entire operating system against the new version (which is exactly what Red Hat will do in RHEL 7.4).

* maintenance burden

The spec file and patch set for OpenSSL are considerably more complex than the end user applications we are used to packaging.  This combined with the critical nature of OpenSSL itself makes me feel more comfortable leaving this one in the hands of Red Hat's army of developers, rather than our small IUS team.

**Comment by stylobille** [comment]
Hello,

Yes, all your points make perfect sense and I didn't think of most, so yes clearly offering OpenSSL 1.0.2 as a replacement for OpenSSL 1.0.1e-fips is probably a bad idea and having your current httpd24u-2.4.20 with OpenSSL 1.0.2 also.

So how about a dedicated http 2.0 branch that installs somewhere else and is completely independent ? 
This would allow for the people that explicitly want http 2.0 to use that and not screw up the rest of the system and then, once http 2.0 is completely working with redhat 7.4, you can depreciate the whole branch. 
This will of course force users to migrate from your dedicate branch to the standard httpd24u (in about a year or so) but that is quite simple, some conf files to copy and then you're good to go.

I would suggest of naming the new packages like httpd24u-2.4.20-openssl1.0.2h // httpd24u-mod_ssl-2.4.20-openssl1.0.2h etc... And maybe install it in /opt ?

Of course this doesn't remove the complexity of compiling OpenSSL 1.0.2...

Well anyway, I would be happy with such a solution, but then again, I don't know how much work this asks from you and I don't have the knowledge to do it myself, so I really hope you are up for this ;)

**Comment by ralfbecker** [comment]
That approach would also work with Nginx: using there spec, compile it together with openssl-1.0.2 (it compiles in openssl static) and create an Nginx 1.10.1 package for RHEL7 containing Nginx using OpenSSL-1.0.2 and there for supporting HTTP/2.

That would reduce compatibility issues to just Nginx (or Apache 2.4 in stylobille's case).

What do you think about that approach Carl?

**Comment by carlwgeorge** [comment]
Most IUS packages are designed to live in the stock locations.  If you are interested in parallel installations in /opt, [Software Collections](https://www.softwarecollections.org) may be just what you need.  Bundling OpenSSL within our packages is not something we are interested in.

**Comment by divad** [comment]
Red Hat plan to rebase to 1.0.2 in RHEL 7.4 - so this request should be closed.

**Comment by carlwgeorge** [comment]
Agreed.

**Comment by carlwgeorge** [comment]
Confirmed in the RHEL 7.4 Beta release notes.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7-Beta/html/7.4_Release_Notes/new_features_security.html#BZ1276310

**Comment by dev31000** [comment]
Was able to resolve the dependency after switching from CentOS 7.3 to 7.4
