### ISSUE TITLE
php70u-pecl-mongo

### ISSUE THREAD

**Issue by MrPrimate** [iuscommunity/wishlist#72]
### What package do you want?

mongo

### Why?

I would like to be able to deploy the mongo driver via RPM.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by remicollet** [comment]
pecl/mongo will never be compatible with php 7

**Comment by MrPrimate** [comment]
Ah yes, sorry, got myself in a naming kefuffle. Thanks

**Comment by carlwgeorge** [comment]
The mongo extension has been deprecated in favor of a newer mongodb extension, which is compatible with PHP 7 (as of [version 1.1.1](https://pecl.php.net/package/mongodb/1.1.1)).  Currently IUS only ships the mongo extension for php55u and php56u, only because we have not yet received a request for the mongodb extension.  @MrPrimate, would a php70u-pecl-mongodb package (using the newer extension of course) work for your needs?

**Comment by MrPrimate** [comment]
Unfortunately no, I was looking at some requirements for running a doctrine app on PHP7, but they currently don't support the newer mongodb package. Thanks anyway.
