### ISSUE TITLE
php*u-pecl-smbclient

### ISSUE THREAD

**Issue by ralfbecker** [iuscommunity/wishlist#74]
### What package do you want?

php(56|70)u-pecl-smbclient

### Why?

It contains php bindings for smbclient library and a smb stream wrapper.
It is used eg. in owncloud to access samba shares. We use our own - never published - extension currently, which does not support php 7.0+. PECL smbclient (https://pecl.php.net/package/smbclient) already has a release supporting php 7 and Remi has build it for Fedora, so it should be a relativ easy addition to IUS.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @ralfbecker,

Thanks for taking the time to submit this request.  

First, a little bit of background information.  Remi has built php-smbclient packages for both [Fedora][0] and [his Remi Repo][1].  The package were created before this module was in pecl, so that is why the package name does not include the word 'pecl'.

I must admit, my initial reaction was f*$@ing Windows.  After that initial reaction, I was wondering why one would use this module verse having the system mount a SMB share that the owncloud (or others) have access to.  Maybe in an involvement where the user does not have root access?

-Ben


[0]: http://koji.fedoraproject.org/koji/buildinfo?buildID=740711
[1]: http://rpms.remirepo.net/fedora/24/php70/x86_64/repoview/php-smbclient.html

**Comment by ralfbecker** [comment]
Hi Ben,
I'm not using owncloud, but my own project EGroupware. If we integrate with an AD, smbclient allows us to connect to arbitrary shares or eg, users home as that user by using his credentials from an active session. That way webserver has no credentials at all and breaking into webserver reveals no data.
Ralf

**Comment by b-harper** [comment]
@ralfbecker,

Ahh... that is a use case that did not cross my mind.  I will look what it will take to create php56u-pecl-smbclient and php70u-pecl-smbclient packages.


-Ben

**Comment by b-harper** [comment]
@ralfbecker,

I have some initial  php70u-pecl-smbclient packages built and will be placed in the testing repositories during tonight's automation run.  Let us know if they work for your use case.

-Ben

**Comment by carlwgeorge** [comment]
@ralfbecker Any update on testing this?

**Comment by ralfbecker** [comment]
Sorry, I'm quite busy currently.

I made the necessary changes to use it in our software (www.egroupware.org), but so far I was not able to make the necessary test.

Please be a little more patient with me.

Ralf

**Comment by ralfbecker** [comment]
Hi Carl,
I was able to test smb stream-wrapper / php70u-pecl-smb package and it works correct for me.
So from my perspective it can be moved from testing repo to stable.
Ralf

**Comment by carlwgeorge** [comment]
Thanks for getting back to us @ralfbecker.  This package will get promoted to the stable repositories during tonight's automation.  Thanks for participating in IUS!
