### ISSUE TITLE
memcached14u

### ISSUE THREAD

**Issue by ficus** [iuscommunity/wishlist#8]
The stock memcached in el6 is version 1.4.4.  In memcached 1.4.22 there have been a number of fixes as well as performance improvements.  @dormando referred to 1.4.4 as ancient.   Please consider creating a 1.4.22 package for IUS.  It would compliment well other packages there already such as the pecl memcached client modules for  Thanks!

**Comment by cgtx** [comment]
Howdy @ficus,

Thanks for reaching out to us today.  Here is our review process for new package requests.

* Is it a good fit for IUS?
* Is it maintainable with our current resources?
* After building the package, is the requester willing to test the package to ensure expected behavior?

I'm going to do some research on this software and get back to you.  If you can find any documented benchmarks that demonstrate the performance improvements, that would positively help our decision process in favor of proceeding with this.  Also, a list of the specific fixes that matter to you would be useful.

**Comment by carlgeorge** [comment]
Looks like there are several CVEs that Red Hat rated as "Low" and chose not to backport to the stock EL6 package.

https://access.redhat.com/security/cve/CVE-2011-4971 (affects <=1.4.5)
https://access.redhat.com/security/cve/CVE-2013-0179 (affects <1.4.17)
https://access.redhat.com/security/cve/CVE-2013-7290 (affects <1.4.17)
https://access.redhat.com/security/cve/CVE-2013-7291 (affects <1.4.17)

Creating this package would address these, since it would use the latest upstream version (1.4.24).

**Comment by ficus** [comment]
Howdy,
There are quite a few changes.  Release notes are listed here:  https://code.google.com/p/memcached/wiki/ReleaseNotes

Having just started to delve into this project I can't yet speak to any specific issues our application might encounter using the older version.  Nothing specific I am trying to work around.  More preventative.

Finally I would mention that getting any support on a version that is almost 6 years old is difficult.  The age of the release and the number of changes made since are my main reasoning.

On that final bullet point I will gladly help to test.

**Comment by carlgeorge** [comment]
I completed a build for memcached14u version 1.4.24.  It will move to our testing repos with tonight's automation.  Give it a shot and let us know if you notice anything wrong with it.

**Comment by ficus** [comment]
Had no issues installing package(s) on CentOS 6.6 (Final).

libmemcached10.x86_64              1.0.16-1.ius.el6                  @ius
memcached14u.x86_64                1.4.24-1.ius.centos6          @ius-test
memcached14u-devel.x86_64       1.4.24-1.ius.centos6         @ius-test

Tried on a fresh install and on on server where memcached-1.4.4-3.el6.x86_64 had been installed.

Other repositories in environment are:
base			CentOS-6 - Base
drivesrvr		drivesrvr
epel			Extra Packages for Enterprise Linux 6 - x86_64
extras		CentOS-6 - Extras
ius			IUS Community Packages for Enterprise Linux 6 - x86_64
ius-test		TEST IUS Community Packages for Enterprise Linux 6 - x86_64
rackspace	Rackspace Monitoring
updates		CentOS-6 - Updates 

If there is anything else specifically I can help to test just let me know.  Thanks for following up on this request!

**Comment by carlgeorge** [comment]
Any further testing past just installing would be appreciated.  Also, I'm curious if this works fine with stock libmemcached.  I didn't noticed an explicit dependency between the two.

**Comment by carlgeorge** [comment]
@ficus Have you had a chance to test this anymore?  I'd like to push this to our stable repos, but just being able to install the rpm isn't enough testing.  Can you find a way to test the functionality further?  Maybe deploy it on a test server the same way you would in production if we were to promote it to stable?

**Comment by carlgeorge** [comment]
Per our conversation in IRC, I'm going to move this package to our development repository for now.  Let me know when you get a chance to evaluate the package further.

**Comment by b-harper** [comment]
I am going to close this issue.  If needed, we can reopen this issue.
