### ISSUE TITLE
php56u-pecl-rrd

### ISSUE THREAD

**Issue by miguelgm** [iuscommunity/wishlist#83]
### What package do you want?

pecl-rrd for php56u

### Why?

There is a version for php54 in epel but not for php56u in IUS.

### OS versions

I would like it for CentOS 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @miguelgm,

Thanks for submitting this request.  Looking over things, this package seems fairly straightforward.  The only thing that will need special consideration is that the upstream uses version 1.x.x for PHP5, and 2.x.x for PHP7.  I'll start working on porting the Fedora spec file.

**Comment by carlwgeorge** [comment]
I have completed an [initial build](https://github.com/iuscommunity-pkg/php56u-pecl-rrd/releases/tag/1.1.3-1.ius).  It will move to the testing repositories during tonight's automation.  I know you only asked for the build for CentOS (EL)7, but since we build php56u for both EL6 and EL7, I built this package for both EL6 and EL7 as well.  If you are able to test it on both it would be highly appreciated, but if you are only able to test on EL7 then that is fine.

**Comment by miguelgm** [comment]
Great, thank you!
We will test it on CentOS 6 also, no problem on that.
As I go on vacation today, I'm putting another colleague in charge of this and I will let report the test results during the third week of August.

**Comment by b-harper** [comment]
@miguelgm,

I just wanted to check in and see if you and your team have had a chance to test this package.

**Comment by miguelgm** [comment]
@b-harper sorry, I completely forgot about this after vacation :-/

@carlwgeorge, I already built it for CentOS 7 and CentOS 6 64. The SPEC worked flawlessly and built without any errors. I also tested several of the php-rrd functions and they worked fine.
Do you need any kind of report or log from the builds?
Thank you

**Comment by carlwgeorge** [comment]
Thanks for testing.  We've got our own build logs as well, we were mainly interested in if the final package worked as expected.  Since you confirmed that the php-rrd functions work, that is good enough for us to promote the package.  I will move to the stable repositories during tonight's automation.
