### ISSUE TITLE
php56u-pecl-oci8

### ISSUE THREAD

**Issue by pmelon** [iuscommunity/wishlist#96]
### What package do you want?

php56u-pecl-oci8

### Why?

We have a production EL6 server with php56u installed and have developed a requirement for the pecl-oci8 package, which is currently unavailable.

### OS versions

I would like this package for both RHEL 6 and 7, with EL6 being the priority.

### Testing

I absolutely agree to test the new package to ensure that it works as expected because I have a project manager pestering me as to when it'll be done.

**Comment by b-harper** [comment]
Hello @pmelon,

Thanks for taking the time to make this request.  This package does fit within the scope of the IUS project and I will take a look at creating an intial pacakge.  Like php56u-mssql, we (IUS) will be very limited when it comes to trouble shooting any issues that might come up as we don't have access to an Oracle database.


-Ben

**Comment by pmelon** [comment]
That's great. I'll troubleshoot, no problem!

**Comment by b-harper** [comment]
Taking a closer look, it appears that some Oracle code is needed, either in the form of the Oracle database itself or the Oracle Instant Client, per the [README][0].  Niether option is straight forward for us to handle.  The [Instant Client is available][1], but envolves the [OTN Development and Distribution License Agreement for Instant Client][2].  

This seems much more involved than a standard pecl module and I am starting to question if we should proceed with this request.  

[0]: http://git.php.net/?p=php-src.git;a=blob_plain;f=ext/oci8/README;hb=refs/heads/master
[1]: http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
[2]: http://www.oracle.com/technetwork/licenses/instant-client-lic-152016.html

**Comment by b-harper** [comment]
The main [Oracle Instant Client][4] page goes out of its way to mention the license and checking with you legal team.  Also, the Instant Client can be downloaded, but only after agreeing to the license and logging into their site.  I am starting to see why Red Hat and Fedora do not provide this module in their standard repositories.  I think IUS should follow suit.  It is unfortunate that Oracle makes this so much harder than it needs to be.


[4]: http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html

**Comment by remicollet** [comment]
@pmelon For your information, the oracle extension is one of the reason I create [my repo](https://rpms.remirepo.net/) more than [10 years](https://blog.remirepo.net/post/2005/08/26/35-php-oci8-504-104) ago, so [php-oci8](https://rpms.remirepo.net/enterprise/6/php56/x86_64/repoview/php-oci8.html) package has always be available there.

Notice:
* indeed, Oracle dependencies can not be redistribute (because of export restriction clause, and because of license approval process)
* php-pecl-oci8 only make sense for PHP <= 5.5
* installation is a bit more complex than other ext, as it requires environment tweaking

**Comment by pmelon** [comment]
Thanks both.

@b-harper - it makes sense. Thanks for even considering it.

@remicollet - the IUS repo is used in production here, which was before my time, but all my stuff (and what will become production eventually) relies on your repo. Why does php-pecl-oci8 only make sense for PHP <= 5.5? I have a multi-PHP version box in dev with 5.4, 5.6, 7.0 and 7.1 (the last three from your repo) and they all have an OCI package available. Not arguing, just curious.

**Comment by remicollet** [comment]
>  Why does php-pecl-oci8 only make sense for PHP <= 5.5

Because:
* php-oci8, built from php sources (not from pecl sources) provides both "oci8" and "pdo_oci" extensions (while pecl/oci8 only provides "oci8")
* ext/oci8 in 5.6 provides version 2.0.12 (so same version than pecl)
* ext/oci8 in 7.x provides version 2.1.3 (so same version than pecl)
* ext/oci8 in 5.5 provides version 1.4.10, so here the pecl version is greater and thus make sense.

**Comment by b-harper** [comment]
I am closing out stale issues.  This can be reopened if needed.
